// T6 — All-Controls runtime driver.
//
// Generated by tests/t6-allcontrols/all-controls.test.js.
// Drives the USER's generated MainWindow (which carries a TabControl with every
// toolbox control on its own tab) under Avalonia.Headless or on the live platform,
// then asserts:
//   - the window is created,
//   - the TabControl ("AllControlsTab") is found and has the expected tab count,
//   - each tab can be selected and IsSelected becomes true,
//   - every toolbox control on every tab is FindControl'd by its snippet name and
//     has non-zero rendered bounds.
//
// Prints one "PASS/FAIL name detail" line per check and a final "RESULT PASS|FAIL".
// Exit code 0 = all checks passed.
//
// Placeholders replaced by the test.  Names are listed WITHOUT braces on purpose: the substitution
// is plain text replacement (this comment included), so writing the braced TAB_DATA token in here
// would inject the generated tuple block into the middle of the comment and break the build.
//   NAMESPACE           — the generated project's root namespace
//   HEADLESS_CALL       — ".UseHeadless(new AvaloniaHeadlessPlatformOptions())" or ".UsePlatformDetect()"
//   SETTLE_MS           — milliseconds to wait for initial layout
//   IS_LIVE             — "true" in live mode, "false" in headless mode
//   TABCONTROL_NAME     — the x:Name of the TabControl in the generated XAML
//   TAB_COUNT           — the expected number of TabItems
//   TAB_DATA            — inline declarations of (header, controlNames[]) tuples
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Headless;
using Avalonia.Threading;
using {NAMESPACE};

internal static class Program
{
    private static int _fails;
    // A plain readonly field rather than a substituted constant, so the branch for the OTHER
    // platform mode stays reachable and the compiler does not report CS0162 "unreachable code".
    private static readonly bool IsLive = {IS_LIVE};
    private static Window? _window;

    private static void Check(bool cond, string name, string detail = "")
    {
        Console.WriteLine((cond ? "PASS " : "FAIL ") + name + (detail.Length > 0 ? " " + detail : ""));
        if (!cond) _fails++;
    }

    private static void Layout(Window w)
    {
        w.Measure(Size.Infinity);
        w.Arrange(new Rect(0, 0, w.ClientSize.Width, w.ClientSize.Height));
        Dispatcher.UIThread.RunJobs();
    }

    private static void RunChecks()
    {
        var window = _window!;   // Main() always assigns this before RunChecks()
        Layout(window);
        Thread.Sleep({SETTLE_MS});
        Layout(window);
        Dispatcher.UIThread.RunJobs();

        Check(window.GetType() == typeof(MainWindow), "window-created", window.GetType().Name);

        var tabCtl = window.FindControl<TabControl>("{TABCONTROL_NAME}");
        Check(tabCtl != null, "tabcontrol-found", tabCtl == null ? "missing {TABCONTROL_NAME}" : "");
        Check(tabCtl != null && tabCtl.Items.Count == {TAB_COUNT}, "tab-count",
            tabCtl != null ? $"expected={TAB_COUNT} actual={tabCtl.Items.Count}" : "no tabcontrol");

        if (tabCtl != null)
        {
            var tabs = new[]
            {
{TAB_DATA}
            };

            for (int ti = 0; ti < tabs.Length && ti < tabCtl.Items.Count; ti++)
            {
                var item = tabCtl.Items[ti] as TabItem;
                Check(item != null, "tab-item:" + ti, item == null ? "null TabItem" : "");
                if (item == null) continue;

                item.IsSelected = true;
                Dispatcher.UIThread.RunJobs();
                Layout(window);
                Check(item.IsSelected, "tab-selected:" + ti, $"header=\"{tabs[ti].header}\"");

                foreach (var ctrlName in tabs[ti].controls)
                {
                    var ctrl = window.FindControl<Control>(ctrlName);
                    Check(ctrl != null, "control-found:" + ctrlName, ctrl == null ? "missing" : "");
                    if (ctrl != null)
                    {
                        Check(ctrl.Bounds.Width > 0 && ctrl.Bounds.Height > 0, "control-size:" + ctrlName,
                            $"bounds={ctrl.Bounds.Width:F0}x{ctrl.Bounds.Height:F0}");
                    }
                }
            }
        }
    }

    [STAThread]
    public static int Main()
    {
        try
        {
            var appBuilder = AppBuilder.Configure<App>()
                {HEADLESS_CALL}
                .UseSkia();

            if (IsLive)
            {
                // Live platform: initialise the real desktop lifetime so window.Show()
                // creates an actual native window on the screen.  The checks run on the
                // UI thread via Post(); closing the window (or the 30s timeout) stops MainLoop.
                var lifetime = new ClassicDesktopStyleApplicationLifetime();
                appBuilder.SetupWithLifetime(lifetime);
                _window = new MainWindow();
                _window.Show();
                Dispatcher.UIThread.Post(() =>
                {
                    Layout(_window);
                    Thread.Sleep({SETTLE_MS});
                    Layout(_window);
                    Dispatcher.UIThread.RunJobs();
                    RunChecks();
                    Console.WriteLine("RESULT " + (_fails == 0 ? "PASS" : "FAIL"));
                    Thread.Sleep({SETTLE_MS});
                    _window.Close();
                }, DispatcherPriority.Background);
                var cts = new CancellationTokenSource(TimeSpan.FromSeconds(30));
                _window.Closed += (_, _) => cts.Cancel();
                Dispatcher.UIThread.MainLoop(cts.Token);
                return _fails == 0 ? 0 : 1;
            }
            else
            {
                // Headless: no message loop — RunJobs() processes layout in-process.
                appBuilder.SetupWithoutStarting();
                _window = new MainWindow();
                _window.Show();
                Layout(_window);
                RunChecks();
                Console.WriteLine("RESULT " + (_fails == 0 ? "PASS" : "FAIL"));
                _window.Close();
                return _fails == 0 ? 0 : 1;
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("RESULT FAIL");
            Console.WriteLine("EXCEPTION " + ex);
            return 1;
        }
    }
}
