/* T2 — controlEvents: the generated Avalonia event catalog (the event picker's data).
 *
 * The names/EventArgs types in src/controlEvents.ts were generated by reflecting over the real
 * Avalonia 12.1.1 assemblies, so these assertions guard the SHAPE of that data (a curated list per
 * interactive control, an EventArgs for every listed event, the per-control overrides that resolve
 * the five event names whose args differ between controls) — and the picker's scope.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const ce = require('../../out/controlEvents.js');

const ROOT = path.join(__dirname, '..', '..');

module.exports = async (t) => {
    t.section('controlEvents');

    // ---------- curated lists ----------
    t.equal(ce.EVENTS_BY_CONTROL.Button[0], 'Click', 'curated', 'Button lists Click first');
    t.equal(ce.EVENTS_BY_CONTROL.TextBox[0], 'TextChanged', 'curated', 'TextBox lists TextChanged first');
    t.equal(ce.EVENTS_BY_CONTROL.CheckBox[0], 'IsCheckedChanged', 'curated', 'CheckBox lists IsCheckedChanged first');
    t.equal(ce.EVENTS_BY_CONTROL.ComboBox[0], 'SelectionChanged', 'curated', 'ComboBox lists SelectionChanged first');
    t.ok(ce.EVENTS_BY_CONTROL.DataGrid.includes('CellEditEnding'), 'curated', 'DataGrid offers its edit events');
    t.ok(ce.EVENTS_BY_CONTROL.Border.includes('ContextRequested'), 'curated', 'a Border still has a (non-dropping) list');
    t.ok(!ce.EVENTS_BY_CONTROL.TreeViewItem.includes('SelectionChanged'), 'curated',
        'a TreeViewItem has no SelectionChanged (the dump corrected this)');

    const missingArgs = [];
    const dupes = [];
    for (const [tag, events] of Object.entries(ce.EVENTS_BY_CONTROL)) {
        if (new Set(events).size !== events.length) dupes.push(tag);
        for (const e of events) {
            if (!ce.EVENT_ARGS[e] && !(ce.EVENT_ARGS_BY_CONTROL[tag] ?? {})[e]) missingArgs.push(`${tag}.${e}`);
        }
    }
    t.equal(missingArgs.length, 0, 'curated', 'every curated event has an EventArgs type',
        missingArgs.slice(0, 6).join(', '));
    t.equal(dupes.length, 0, 'curated', 'no curated list repeats an event', dupes.join(', '));

    // ---------- default events ----------
    t.equal(ce.defaultEventFor('Button'), 'Click', 'default', 'Button → Click');
    t.equal(ce.defaultEventFor('DataGrid'), 'SelectionChanged', 'default', 'DataGrid → SelectionChanged');
    t.equal(ce.defaultEventFor('Panel'), 'DoubleTapped', 'default', 'a control without one falls back');
    t.ok(ce.hasDefaultEvent('Button') && ce.hasDefaultEvent('Panel') === false, 'default', 'hasDefaultEvent');
    const defaultNotFirst = Object.keys(ce.DEFAULT_EVENT)
        .filter((tag) => (ce.EVENTS_BY_CONTROL[tag] ?? []).includes(ce.DEFAULT_EVENT[tag]) === false);
    t.equal(defaultNotFirst.length, 0, 'default',
        'every default event is offered by its control (so the picker can preselect it)', defaultNotFirst.join(', '));

    // ---------- the picker's scope ----------
    for (const tag of ['Button', 'CheckBox', 'RadioButton', 'ComboBox', 'ListBox', 'TabControl', 'DataGrid', 'TextBox', 'HyperlinkButton', 'Menu', 'Slider', 'ToggleSwitch']) {
        t.ok(ce.asksForEventOnPlace(tag), 'scope', `${tag} asks when placed`);
    }
    for (const tag of ['Panel', 'Grid', 'Border', 'Image', 'TextBlock', 'Rectangle', 'GroupBox', 'PathPicker', 'SplitPanel', 'StatusDate', 'XYTracker']) {
        t.ok(ce.asksForEventOnPlace(tag) === false, 'scope', `${tag} is placed without asking`);
    }
    const thinLists = ce.EVENT_PICKER_TAGS.filter((tag) => ce.eventsFor(tag).length < 3);
    t.equal(thinLists.length, 0, 'scope', 'every asking control has a usable list', thinLists.join(', '));
    const generic = ce.EVENT_PICKER_TAGS.filter((tag) => ce.EVENTS_BY_CONTROL[tag] === undefined);
    t.equal(generic.length, 0, 'scope', 'no asking control silently falls back to the generic list', generic.join(', '));

    // ---------- fallback ----------
    t.ok(ce.eventsFor('SomeThirdPartyControl').includes('Loaded'), 'fallback', 'an unknown control gets the generic list');
    t.ok(ce.eventsFor('SomeThirdPartyControl').includes('PointerPressed'), 'fallback', 'including the pointer events');
    t.ok(ce.eventsFor('Panel').length > 0, 'fallback', 'a known control gets its curated list');

    // ---------- EventArgs resolution (incl. the per-control overrides) ----------
    t.equal(ce.eventArgsFor('Click'), 'Avalonia.Interactivity.RoutedEventArgs', 'args', 'Click → RoutedEventArgs');
    t.equal(ce.eventArgsFor('Tapped'), 'Avalonia.Input.TappedEventArgs', 'args', 'Tapped → TappedEventArgs');
    t.equal(ce.eventArgsFor('TextChanged'), 'Avalonia.Controls.TextChangedEventArgs', 'args', 'TextChanged → TextChangedEventArgs');
    t.equal(ce.eventArgsFor('DropDownOpened', 'ComboBox'), 'System.EventArgs', 'args',
        'an EventHandler event (DropDownOpened) → EventArgs');
    t.equal(ce.eventArgsFor('Opening', 'CommandBar'), 'Avalonia.Interactivity.RoutedEventArgs', 'args',
        'a known event outside the curated lists still resolves (Opening)');
    t.equal(ce.eventArgsFor('NotARealEventAtAll'), 'Avalonia.Interactivity.RoutedEventArgs', 'args',
        'an unknown event name falls back to RoutedEventArgs');
    t.equal(ce.eventArgsFor('Opened', 'Window'), 'System.EventArgs', 'args', 'Window.Opened → EventArgs');
    t.equal(ce.eventArgsFor('Opened', 'Menu'), 'Avalonia.Interactivity.RoutedEventArgs', 'args', 'Menu.Opened → RoutedEventArgs');
    t.equal(ce.eventArgsFor('Closed', 'WindowBase'), 'System.EventArgs', 'args', 'WindowBase.Closed → EventArgs');
    t.equal(ce.eventArgsFor('Closing', 'Window'), 'Avalonia.Controls.WindowClosingEventArgs', 'args',
        'Window.Closing → WindowClosingEventArgs');
    t.equal(ce.eventArgsFor('ValueChanged', 'NumericUpDown'), 'Avalonia.Controls.NumericUpDownValueChangedEventArgs', 'args',
        'NumericUpDown.ValueChanged is the odd one out');
    t.equal(ce.eventArgsFor('ValueChanged', 'Slider'), 'Avalonia.Controls.Primitives.RangeBaseValueChangedEventArgs', 'args',
        'Slider.ValueChanged uses the RangeBase args');
    t.equal(ce.eventArgsFor('SelectedDateChanged', 'DatePicker'), 'Avalonia.Controls.DatePickerSelectedValueChangedEventArgs', 'args',
        'DatePicker.SelectedDateChanged is the odd one out');
    t.equal(ce.eventArgsFor('SelectedDateChanged', 'CalendarDatePicker'), 'Avalonia.Controls.SelectionChangedEventArgs', 'args',
        'CalendarDatePicker.SelectedDateChanged uses SelectionChangedEventArgs');

    // ---------- isKnownEvent ----------
    t.ok(ce.isKnownEvent('ComboBox', 'DropDownOpened'), 'known', 'a picker event is recognised');
    t.ok(ce.isKnownEvent('Panel', 'Loaded'), 'known', 'a generic event is recognised');
    t.ok(ce.isKnownEvent('Button', 'NotAnEvent') === false, 'known', 'a random name is not an event');

    // ---------- the reference document exists and matches the catalog ----------
    const refPath = path.join(ROOT, 'Events per Control.md');
    const ref = fs.existsSync(refPath) ? fs.readFileSync(refPath, 'utf8') : '';
    t.ok(ref.length > 5000, 'reference', 'Events per Control.md exists and has content');
    t.ok(/Avalonia 12\.1\.1/.test(ref), 'reference', 'it names the Avalonia version it was generated from');
    for (const tag of ['Button', 'DataGrid', 'Window', 'ComboBox']) {
        t.ok(new RegExp(`^### ${tag}\\b`, 'm').test(ref), 'reference', `${tag} has a section in the reference`);
    }
    t.ok(ref.includes('DropDownOpened'), 'reference', 'the reference lists real events (DropDownOpened)');
    t.ok(ref.includes('CellEditEnding'), 'reference', 'and control-specific ones (DataGrid.CellEditEnding)');

    // ---------- integration: a picker-wired event is stripped from the PREVIEW but kept on save ----------
    // (the host has no code-behind, so a handler attribute left in the preview XAML fails the load)
    const { XamlModel } = require('../../out/xamlModel.js');
    const axaml = `<?xml version="1.0"?>
<Window xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
  <Canvas Name="Body">
    <ComboBox x:Name="ComboBox1" DropDownOpened="ComboBox1_DropDownOpened" Opening="ComboBox1_Opening"/>
  </Canvas>
</Window>`;
    {
        const model = new XamlModel(axaml);
        const preview = model.serialize(false);
        const saved = model.serialize(true);
        t.ok(preview.includes('DropDownOpened') === false, 'strip',
            'a picker-wired event (DropDownOpened) is stripped from the preview XAML');
        t.ok(preview.includes('Opening') === false, 'strip', 'so is another catalog event (Opening)');
        t.ok(saved.includes('DropDownOpened="ComboBox1_DropDownOpened"'), 'strip', 'but the saved file keeps it');
        t.ok(saved.includes('ComboBox1_Opening'), 'strip', 'and keeps the other one too');
    }

    // ---------- integration: the generated C#/VB stubs carry the catalog's EventArgs type ----------
    {
        const os = require('os');
        const { Uri } = require('vscode');
        const { insertHandlerIntoCodeBehind } = require('../../out/codeBehind.js');
        const mkProject = (ext, body) => {
            const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'adb-eventargs-'));
            const p = path.join(dir, 'TestForm.axaml');
            fs.writeFileSync(p, axaml);
            fs.writeFileSync(path.join(dir, `TestForm.axaml.${ext}`), body);
            return { dir, p };
        };
        const vb = mkProject('vb', `Imports Avalonia.Controls

Class TestForm
    Inherits Window

    Public Sub New()
        InitializeComponent()
    End Sub
End Class
`);
        const cs = mkProject('cs', `using Avalonia.Controls;
namespace Proj;
public partial class TestForm : Window
{
    public TestForm()
    {
        InitializeComponent();
    }
}
`);
        for (const [kind, ev] of [['DropDownOpened', 'DropDownOpened'], ['o', 'Opening'], ['k', 'KeyDown']]) {
            await insertHandlerIntoCodeBehind(Uri.file(vb.p), `ComboBox1_${ev}`, ev, 'ComboBox');
            await insertHandlerIntoCodeBehind(Uri.file(cs.p), `ComboBox1_${ev}`, ev, 'ComboBox');
            void kind;
        }
        const vbText = fs.readFileSync(path.join(vb.dir, 'TestForm.axaml.vb'), 'utf8');
        const csText = fs.readFileSync(path.join(cs.dir, 'TestForm.axaml.cs'), 'utf8');
        t.ok(/Sub ComboBox1_DropDownOpened\(sender As Object, e As System\.EventArgs\)/.test(vbText), 'stub',
            'VB: an EventHandler event gets System.EventArgs (VB rejects a wrong signature)');
        t.ok(/Sub ComboBox1_Opening\(sender As Object, e As Avalonia\.Interactivity\.RoutedEventArgs\)/.test(vbText), 'stub',
            'VB: Opening gets RoutedEventArgs');
        t.ok(/Sub ComboBox1_KeyDown\(sender As Object, e As Avalonia\.Input\.KeyEventArgs\)/.test(vbText), 'stub',
            'VB: KeyDown gets KeyEventArgs');
        t.ok(/void ComboBox1_DropDownOpened\(object sender, System\.EventArgs e\)/.test(csText), 'stub',
            'C#: the stub uses the same exact type');
        t.ok(/void ComboBox1_KeyDown\(object sender, Avalonia\.Input\.KeyEventArgs e\)/.test(csText), 'stub', 'C#: KeyEventArgs too');
    }
};
