/* T2 — xamlHeader: every generated (and designer-saved) .axaml starts with the
 * "Do NOT edit this file manually - Use the Designer to make changes" notice, exactly once,
 * and the notice never confuses the designer (parser, Refresh change detection, backups). */
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const { withDesignerHeader, XAML_DESIGNER_HEADER } = require('../../out/xamlHeader.js');
const { buildAxaml, buildChromeAxaml, TEMPLATES } = require('../../out/formTemplates.js');
const { generateProjectScaffold } = require('../../out/projectScaffold.js');
const { XamlModel } = require('../../out/xamlModel.js');

const HEADER = '<!-- Do NOT edit this file manually - Use the Designer to make changes -->';
const ROOT = path.join(__dirname, '..', '..');
const countIn = (text) => (text.match(/Do NOT edit this file manually/g) || []).length;
const firstLine = (text) => text.split('\n')[0].trim();

module.exports = async (t) => {
    t.section('xaml-header');

    // --- the notice text itself -------------------------------------------------
    t.equal(XAML_DESIGNER_HEADER, HEADER, 'header', 'notice text is fixed (docs/tests quote it)');

    // --- withDesignerHeader: add / idempotency / de-duplication ------------------
    const plain = '<Window>\n  <TextBlock/>\n</Window>\n';
    const once = withDesignerHeader(plain);
    t.ok(once.startsWith(HEADER + '\n'), 'header', 'prepended to the first line');
    t.equal(countIn(once), 1, 'header', 'exactly one notice after adding');
    t.ok(withDesignerHeader(once) === once, 'header', 'applying twice is a no-op (idempotent)');
    t.equal(countIn(withDesignerHeader(once + once)), 1, 'header', 'concatenated bodies collapse to one notice');

    const twice = HEADER + '\n<Window>\n' + HEADER + '\n</Window>\n';
    const deduped = withDesignerHeader(twice);
    t.equal(countIn(deduped), 1, 'header', 'stray copies inside the file are removed');
    t.ok(!/\n\s*\n<Window/.test(deduped), 'header', 'no blank line left where a copy was removed');

    // --- xml declaration + BOM ---------------------------------------------------
    const decl = '\uFEFF<?xml version="1.0" encoding="utf-8"?>\n<Window/>\n';
    const withDecl = withDesignerHeader(decl);
    t.ok(withDecl.startsWith('\uFEFF<?xml'), 'header', 'BOM + <?xml?> declaration stay first');
    t.ok(withDecl.includes('?>\n' + HEADER + '\n'), 'header', 'notice follows the declaration');
    const bomOnly = withDesignerHeader('\uFEFF<Window/>\n');
    t.ok(bomOnly.startsWith('\uFEFF' + HEADER), 'header', 'BOM preserved when there is no declaration');

    // --- generated templates carry it -------------------------------------------
    const axaml = buildAxaml(TEMPLATES[0], 'MainWindow', 'Window', 'Proj');
    t.equal(firstLine(axaml), HEADER, 'templates', 'buildAxaml() starts with the notice');
    const chrome = buildChromeAxaml(TEMPLATES[0], 'MainWindow', 'Proj', 'Proj');
    t.equal(firstLine(chrome), HEADER, 'templates', 'buildChromeAxaml() starts with the notice');

    // --- scaffolded projects (App.axaml + MainWindow.axaml, C# and VB) -----------
    for (const language of ['cs', 'vb']) {
        const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'xamlhdr-'));
        try {
            generateProjectScaffold({
                language, tpl: TEMPLATES[0], name: 'HeaderProbe', projectPath: dir,
                chromeCs: '// c', chromeVb: "' v", anchorCs: '// c', anchorVb: "' v"
            });
            for (const file of ['App.axaml', 'MainWindow.axaml']) {
                const text = fs.readFileSync(path.join(dir, file), 'utf8');
                t.equal(firstLine(text), HEADER, 'scaffold', `${language}: ${file} starts with the notice`);
                t.equal(countIn(text), 1, 'scaffold', `${language}: ${file} has exactly one notice`);
            }
        } finally {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    }

    // --- "New Form" uses the same builder (which stamps the notice) ----------------
    const newFormSrc = fs.readFileSync(path.join(ROOT, 'src', 'newForm.ts'), 'utf8');
    t.ok(newFormSrc.includes('buildAxaml('), 'newForm', 'New Form XAML comes from buildAxaml()');
    t.ok(/writeFile\(axamlUri, Buffer\.from\(axaml/.test(newFormSrc), 'newForm',
        'and that exact string is what gets written');

    // --- designer saves re-stamp it (so a hand-edited/older file gains it too) ----
    const panelSrc = fs.readFileSync(path.join(ROOT, 'src', 'designerPanel.ts'), 'utf8');
    for (const fn of ['saveCustomDocument', 'saveCustomDocumentAs', 'backupCustomDocument']) {
        const body = new RegExp(`async ${fn}\\([^]*?\\n    \\}`).exec(panelSrc);
        t.ok(!!body && body[0].includes('withDesignerHeader'), 'save',
            `${fn}() stamps the notice`);
    }
    const handlerWrite = panelSrc.split('\n').filter((l) => l.includes('writeFile') && l.includes('serialize(true)'));
    t.ok(handlerWrite.length > 0 && handlerWrite.every((l) => l.includes('withDesignerHeader')), 'save',
        'event-handler save stamps the notice');
    const buffered = panelSrc.split('\n').filter((l) => l.includes('Buffer.from') && l.includes('serialize(true)'));
    t.ok(buffered.every((l) => l.includes('withDesignerHeader')), 'save',
        `no buffered .axaml write misses the notice (${buffered.length} site(s))`);
    t.ok(/withDesignerHeader\(text\) !== withDesignerHeader\(doc\.model\.serialize\(true\)\)/.test(panelSrc),
        'refresh', 'Refresh compares header-normalised text (no phantom "external edit")');

    // --- the notice must not break parsing, and survives a save round-trip -------
    const model = new XamlModel(axaml);
    t.ok(model.namedControls().length > 0, 'parse', 'header-prefixed XAML still parses into a model');
    const saved = withDesignerHeader(model.serialize(true));
    t.equal(firstLine(saved), HEADER, 'parse', 'designed-then-saved file keeps the notice');
    t.equal(countIn(saved), 1, 'parse', 'and still has exactly one copy');
    t.ok(!model.serialize(true).includes('Do NOT edit'), 'parse',
        'the model itself drops comments (hence the re-stamp on save)');

    // --- the notice is a plain XML comment: the renderer must ignore it ----------
    t.ok(/^<!--[\s\S]*-->$/.test(HEADER), 'format', 'notice is a valid XML comment on one line');
};
