// Generated by Grumpy's WYSIWYG Designer — DataSet designer. Do not edit by hand.
// Edit DemoDataSet.adset in the designer and re-generate. (2026-09-27)
using System;
using System.Data;
using System.Collections.Generic;
using System.IO;
using Avalonia;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Threading.Tasks;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Layout;
using Avalonia.LogicalTree;
using Avalonia.Platform.Storage;

namespace GrumpyDesignerDemo
{
    public class DemoDataSet
    {
        /// <summary>Builds the DemoDataSet DataSet at runtime (tables + columns).</summary>
        public static DataSet CreateDataSet()
        {
            var ds = new DataSet("DemoDataSet");

            // Images
            var t0 = ds.Tables.Add("Images");
            var c0_0 = t0.Columns.Add("Id", typeof(int));
            c0_0.AllowDBNull = false;
            c0_0.Caption = "ID";
            var c0_1 = t0.Columns.Add("Image", typeof(string));
            c0_1.AllowDBNull = false;
            var c0_2 = t0.Columns.Add("File", typeof(string));
            t0.Rows.Add(0, "Sample", "Sample");

            return ds;
        }

        public static System.Collections.Generic.List<ImagesRow> GetImages()
        {
            var list = new System.Collections.Generic.List<ImagesRow>();
            using var con = DatabaseAdapter.Open("DemoDataSet.db", "CREATE TABLE IF NOT EXISTS \"Images\" (\"Id\" INTEGER PRIMARY KEY AUTOINCREMENT, \"Image\" TEXT NOT NULL, \"File\" TEXT)");
            DatabaseAdapter.EnsureColumns(con, "Images", new[] { "Id INTEGER", "Image TEXT", "File TEXT" });
            using var cmd = con.CreateCommand();
            cmd.CommandText = "SELECT \"Id\", \"Image\", \"File\" FROM \"Images\" ORDER BY rowid";
            using var rd = cmd.ExecuteReader();
            while (rd.Read())
            {
                list.Add(new ImagesRow
                {
                    Id = rd.IsDBNull(0) ? 0 : rd.GetInt32(0),
                    Image = rd.IsDBNull(1) ? null : rd.GetString(1),
                    File = rd.IsDBNull(2) ? null : rd.GetString(2),
                });
            }
            return list;
        }

        // --- Images: SQLite-backed live grid support ---
        private const string _ImagesDb = "DemoDataSet.db";

        public static System.Collections.ObjectModel.ObservableCollection<ImagesRow> LoadImages()
        {
            var rows = new System.Collections.ObjectModel.ObservableCollection<ImagesRow>();
            using var con = DatabaseAdapter.Open(_ImagesDb, "CREATE TABLE IF NOT EXISTS \"Images\" (\"Id\" INTEGER PRIMARY KEY AUTOINCREMENT, \"Image\" TEXT NOT NULL, \"File\" TEXT)");
            DatabaseAdapter.EnsureColumns(con, "Images", new[] { "Id INTEGER", "Image TEXT", "File TEXT" });
            using var cmd = con.CreateCommand();
            cmd.CommandText = "SELECT \"Id\", \"Image\", \"File\" FROM \"Images\" ORDER BY rowid";
            using var rd = cmd.ExecuteReader();
            while (rd.Read())
            {
                rows.Add(new ImagesRow
                {
                    Id = rd.IsDBNull(0) ? 0 : rd.GetInt32(0),
                    Image = rd.IsDBNull(1) ? null : rd.GetString(1),
                    File = rd.IsDBNull(2) ? null : rd.GetString(2),
                });
            }
            rows.Add(new ImagesRow { Id = 0, Image = "+ Add row…", File = "", IsPlaceholder = true });
            return rows;
        }

        public static void SaveImages(System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows)
        {
            using var con = DatabaseAdapter.Open(_ImagesDb, "CREATE TABLE IF NOT EXISTS \"Images\" (\"Id\" INTEGER PRIMARY KEY AUTOINCREMENT, \"Image\" TEXT NOT NULL, \"File\" TEXT)");
            DatabaseAdapter.EnsureColumns(con, "Images", new[] { "Id INTEGER", "Image TEXT", "File TEXT" });
            using var tx = con.BeginTransaction();
            using (var del = con.CreateCommand())
            {
                del.Transaction = tx;
                del.CommandText = "DELETE FROM \"Images\"";
                del.ExecuteNonQuery();
            }
            foreach (var r in rows)
            {
                if (r.IsPlaceholder) continue;
                if (r.Id != 0)
                {
                    using var ck = con.CreateCommand();
                    ck.Transaction = tx;
                    ck.CommandText = "INSERT INTO \"Images\" (\"Id\", \"Image\", \"File\") VALUES (@p0, @p1, @p2)";
                    ck.Parameters.AddWithValue("@p0", r.Id);
                    ck.Parameters.AddWithValue("@p1", (object?)r.Image ?? System.DBNull.Value);
                    ck.Parameters.AddWithValue("@p2", (object?)r.File ?? System.DBNull.Value);
                    ck.ExecuteNonQuery();
                }
                else
                {
                    using var cn = con.CreateCommand();
                    cn.Transaction = tx;
                    cn.CommandText = "INSERT INTO \"Images\" (\"Image\", \"File\") VALUES (@c0, @c1)";
                    cn.Parameters.AddWithValue("@c0", (object?)r.Image ?? System.DBNull.Value);
                    cn.Parameters.AddWithValue("@c1", (object?)r.File ?? System.DBNull.Value);
                    cn.ExecuteNonQuery();
                    using (var rid = con.CreateCommand())
                    {
                        rid.Transaction = tx;
                        rid.CommandText = "SELECT last_insert_rowid();";
                        r.Id = (int)Convert.ToInt64(rid.ExecuteScalar()!);
                    }
                }
            }
            tx.Commit();
        }
        private static readonly System.Collections.Generic.List<ImagesSnapshot> _ImagesUndo = new();
        private static readonly System.Collections.Generic.List<ImagesSnapshot> _ImagesRedo = new();
        private static int _ImagesDepth = 5;
        private static ImagesSnapshot? _ImagesPendingEdit;

        private static ImagesSnapshot SnapImages(System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows)
        {
            var s = new ImagesSnapshot();
            var parts = new System.Collections.Generic.List<string>();
            foreach (var r in rows)
                if (!r.IsPlaceholder)
                {
                    s.Rows.Add(new ImagesRow { Id = r.Id, Image = r.Image, File = r.File });
                    parts.Add($"{r.Id}|{r.Image}|{r.File}");
                }
            s.Key = string.Join("\n", parts);
            return s;
        }

        private static void TrimImagesUndo()
        {
            while (_ImagesUndo.Count > _ImagesDepth) _ImagesUndo.RemoveAt(0);
        }

        private static void PushImagesUndo(System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows)
        {
            if (_ImagesDepth <= 0) return;
            _ImagesUndo.Add(SnapImages(rows));
            TrimImagesUndo();
            _ImagesRedo.Clear();
        }

        private static void RestoreImages(System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows, ImagesSnapshot s)
        {
            for (int i = rows.Count - 1; i >= 0; i--)
                if (!rows[i].IsPlaceholder) rows.RemoveAt(i);
            foreach (var r in s.Rows) rows.Insert(rows.Count - 1, r);
            SaveImages(rows);
        }

        private static void UndoImages(System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows)
        {
            if (_ImagesUndo.Count == 0) return;
            _ImagesRedo.Add(SnapImages(rows));
            var s = _ImagesUndo[_ImagesUndo.Count - 1];
            _ImagesUndo.RemoveAt(_ImagesUndo.Count - 1);
            RestoreImages(rows, s);
        }

        private static void RedoImages(System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows)
        {
            if (_ImagesRedo.Count == 0) return;
            _ImagesUndo.Add(SnapImages(rows));
            TrimImagesUndo();
            var s = _ImagesRedo[_ImagesRedo.Count - 1];
            _ImagesRedo.RemoveAt(_ImagesRedo.Count - 1);
            RestoreImages(rows, s);
        }

        public static void BuildImagesColumns(DataGrid grid)
        {
            grid.Columns.Add(new DataGridTextColumn { Header = "ID", Binding = new Avalonia.Data.Binding("Id") });
            grid.Columns.Add(new DataGridTextColumn { Header = "Image", Binding = new Avalonia.Data.Binding("Image") });
            grid.Columns.Add(new DataGridTextColumn { Header = "File", Binding = new Avalonia.Data.Binding("File") });
        }

        public static void WireImagesGrid(DataGrid grid, System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows)
        {
            grid.AutoGenerateColumns = false; // typed columns built below; XAML True only for the designer preview
            BuildImagesColumns(grid);
            grid.ItemsSource = rows;
            _ImagesDepth = 5;
            void HandleUndoKey(Avalonia.Input.KeyEventArgs e)
            {
                if (e.Handled) return;
                if (e.KeyModifiers.HasFlag(Avalonia.Input.KeyModifiers.Control))
                {
                    if (e.Key == Avalonia.Input.Key.U) { UndoImages(rows); e.Handled = true; }
                    else if (e.Key == Avalonia.Input.Key.R) { RedoImages(rows); e.Handled = true; }
                }
            }
            grid.KeyDown += (_, e) => HandleUndoKey(e);
            var undoWin = Avalonia.LogicalTree.LogicalExtensions.FindLogicalAncestorOfType<Window>(grid, true);
            if (undoWin != null) undoWin.KeyDown += (_, e) => HandleUndoKey(e);
            // A cell edit becomes an undo step only if it actually changed the row.
            grid.BeginningEdit += (_, _) => { if (_ImagesDepth > 0) _ImagesPendingEdit = SnapImages(rows); };
            // Persist in-cell edits only when committed (Enter / Tab / click-away); Escape cancels without saving.
            grid.RowEditEnded += (_, e) =>
            {
                if (e.EditAction == Avalonia.Controls.DataGridEditAction.Commit)
                {
                    if (_ImagesPendingEdit != null)
                    {
                        var now = SnapImages(rows);
                        if (now.Key != _ImagesPendingEdit.Key)
                        {
                            _ImagesUndo.Add(_ImagesPendingEdit);
                            TrimImagesUndo();
                            _ImagesRedo.Clear();
                        }
                        _ImagesPendingEdit = null;
                    }
                    SaveImages(rows);
                }
                else _ImagesPendingEdit = null;
            };
            // The blank add-row opens the add dialog; real rows get a right-click Delete.
            // Sorting / scrolling recycle the DataGrid row containers, so a container that once
            // showed the blank add-row can later be bound to an ordinary data row. One shared
            // pointer handler is attached only while a container shows the add-row (removed again
            // on UnloadingRow) and it re-checks the row CURRENT DataContext at press time, so a
            // recycled container never pops the dialog for a reordered data row.
            System.EventHandler<Avalonia.Input.PointerPressedEventArgs> addRowPointer = (rs, re) =>
            {
                if (!re.GetCurrentPoint(grid).Properties.IsLeftButtonPressed) return;
                var addRow = rs as DataGridRow;
                if (addRow == null || !(addRow.DataContext is ImagesRow d) || !d.IsPlaceholder) return;
                re.Handled = true;
                _ = AddImagesRow(grid, rows);
            };
            grid.LoadingRow += (_, e) =>
            {
                var data = e.Row.DataContext as ImagesRow;
                if (data == null) return;
                if (data.IsPlaceholder)
                {
                    e.Row.AddHandler(Avalonia.Input.InputElement.PointerPressedEvent, addRowPointer, Avalonia.Interactivity.RoutingStrategies.Bubble, true);
                }
                else
                {
                    var menu = new ContextMenu();
                    var delItem = new MenuItem { Header = "Delete row" };
                    delItem.Click += (_, _) => _ = DeleteImagesRow(grid, rows, data);
                    menu.Items.Add(delItem);
                    e.Row.ContextMenu = menu;
                }
            };
            grid.UnloadingRow += (_, e) => e.Row.RemoveHandler(Avalonia.Input.InputElement.PointerPressedEvent, addRowPointer);
        }

        public static async System.Threading.Tasks.Task AddImagesRow(DataGrid grid, System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows)
        {
            var nextId = 1;
            foreach (var r in rows) { if (!r.IsPlaceholder && r.Id >= nextId) nextId = r.Id + 1; }
            var dlg = new ImagesEditDialog(CreateDataSet().Tables["Images"]!, null, nextId);
            var owner = OwnerOf(grid);
            if (owner != null && await dlg.ShowDialog<bool>(owner))
            {
                var row = dlg.NewRow();
                PushImagesUndo(rows);
                rows.Insert(rows.Count - 1, row);
                SaveImages(rows);
            }
        }

        public static async System.Threading.Tasks.Task EditImagesRow(DataGrid grid, System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows, ImagesRow row)
        {
            var dlg = new ImagesEditDialog(CreateDataSet().Tables["Images"]!, row);
            var owner = OwnerOf(grid);
            if (owner != null && await dlg.ShowDialog<bool>(owner)) { dlg.ApplyTo(row); SaveImages(rows); }
        }

        public static async System.Threading.Tasks.Task DeleteImagesRow(DataGrid grid, System.Collections.ObjectModel.ObservableCollection<ImagesRow> rows, ImagesRow row)
        {
            var dlg = new ConfirmDialog("Delete row", "Delete the selected row?");
            var owner = OwnerOf(grid);
            if (owner != null && await dlg.ShowDialog<bool>(owner))
            {
                PushImagesUndo(rows);
                rows.Remove(row);
                SaveImages(rows);
            }
        }

        private static Window? OwnerOf(DataGrid grid) => Avalonia.LogicalTree.LogicalExtensions.FindLogicalAncestorOfType<Window>(grid, true);
    }

    /// <summary>Locates the files the generated code reads and writes at runtime.</summary>
    public static class RuntimeStorage
    {
        private static string? _folder;
        /// <summary>Per-user folder for this app's data (~/.local/share/App on Linux, %LOCALAPPDATA%\App on Windows) - created on first use.</summary>
        public static string Folder
        {
            get
            {
                if (_folder != null) return _folder;
                var name = typeof(DemoDataSet).Assembly.GetName().Name ?? "app";
                var root = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
                if (root.Length == 0) root = Path.GetTempPath();
                var dir = Path.Combine(root, name);
                try { Directory.CreateDirectory(dir); } catch { /* the failing write reports it */ }
                _folder = dir;
                return dir;
            }
        }
        /// <summary>Absolute path of a runtime data file: the per-user copy when it exists, else a
        /// file of that name beside the executable (an earlier build wrote it there), else the
        /// per-user location - which the caller then creates.</summary>
        public static string PathFor(string name)
        {
            var user = Path.Combine(Folder, name);
            if (File.Exists(user)) return user;
            var beside = Path.Combine(AppContext.BaseDirectory, name);
            if (File.Exists(beside)) return beside;
            return user;
        }
    }

    /// <summary>Small SQLite helper shared by the tables the DataSet designer stores in a database file.</summary>
    public static class DatabaseAdapter
    {
        private static bool _ready;
        private static readonly object Sync = new();
        private static void EnsureReady()
        {
            lock (Sync) { if (_ready) return; _ready = true; global::SQLitePCL.Batteries_V2.Init(); }
        }
        /// <summary>Absolute path of a database file (relative paths resolve to the per-user data folder).</summary>
        public static string DbPath(string file) => Path.IsPathRooted(file) ? file : RuntimeStorage.PathFor(file);
        /// <summary>Opens the database (creating the file if needed) and runs an idempotent CREATE TABLE.</summary>
        public static Microsoft.Data.Sqlite.SqliteConnection Open(string file, string createSql)
        {
            EnsureReady();
            var con = new Microsoft.Data.Sqlite.SqliteConnection("Data Source=" + DbPath(file));
            con.Open();
            if (!string.IsNullOrEmpty(createSql)) { using var cmd = con.CreateCommand(); cmd.CommandText = createSql; cmd.ExecuteNonQuery(); }
            return con;
        }
        /// <summary>Brings an existing table in line with the designer schema: adds any columns
        /// the DataSet has but the DB table lacks (so 'add column → Generate Code' works on an
        /// existing file without losing its rows). New columns are added nullable.</summary>
        public static void EnsureColumns(Microsoft.Data.Sqlite.SqliteConnection con, string table, string[] cols)
        {
            var existing = new System.Collections.Generic.HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            using (var c = con.CreateCommand())
            {
                c.CommandText = $"PRAGMA table_info(\"{table}\")";
                using var rd = c.ExecuteReader();
                while (rd.Read()) existing.Add(rd.GetString(1));
            }
            foreach (var col in cols)
            {
                var name = col.Split(' ')[0];
                var affinity = col.Substring(name.Length).Trim();
                if (existing.Contains(name)) continue;
                using var a = con.CreateCommand();
                a.CommandText = $"ALTER TABLE \"{table}\" ADD COLUMN \"{name}\" {affinity}";
                a.ExecuteNonQuery();
            }
        }
    }

    public class ImagesRow : System.ComponentModel.INotifyPropertyChanged
    {
        private int _Id = default;
        public int Id
        {
            get => _Id;
            set { if (_Id != value) { _Id = value; OnPropertyChanged(nameof(Id)); } }
        }
        private string? _Image;
        public string? Image
        {
            get => _Image;
            set { if (_Image != value) { _Image = value; OnPropertyChanged(nameof(Image)); } }
        }
        private string? _File;
        public string? File
        {
            get => _File;
            set { if (_File != value) { _File = value; OnPropertyChanged(nameof(File)); } }
        }
        [System.ComponentModel.DataAnnotations.Display(AutoGenerateField = false)]
        public bool IsPlaceholder { get; set; }

        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
        private void OnPropertyChanged(string name) => PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(name));
        public override string ToString() => Convert.ToString(Image) ?? "";
    }

    public class ImagesSnapshot
    {
        public System.Collections.Generic.List<ImagesRow> Rows = new();
        public string Key = "";
    }

    /// <summary>Remembers the folder the row dialogs' "Browse…" picker used last (best-effort).</summary>
    public static class FilePickerMemory
    {
        private static string? _folder;
        private static bool _loaded;
        private static string StorePath => RuntimeStorage.PathFor("DemoDataSet.lastfolder");
        /// <summary>The folder the last Browse… dialog used (null = let the OS pick its default).</summary>
        public static string? LastFolder
        {
            get
            {
                if (!_loaded)
                {
                    _loaded = true;
                    try { if (File.Exists(StorePath)) _folder = File.ReadAllText(StorePath).Trim(); } catch { /* best effort */ }
                }
                return _folder;
            }
            set
            {
                _loaded = true;
                _folder = value;
                try
                {
                    if (string.IsNullOrEmpty(value)) { if (File.Exists(StorePath)) File.Delete(StorePath); }
                    else File.WriteAllText(StorePath, value);
                }
                catch { /* best effort (read-only app folder) */ }
            }
        }
    }

    public class ImagesEditDialog : Window
    {
        private readonly System.Data.DataTable _table;
        private NumericUpDown idInput = null!;
        private TextBox imageInput = null!;
        private TextBox fileInput = null!;

        public ImagesEditDialog(System.Data.DataTable table, ImagesRow? row, int? newKey = null)
        {
            _table = table;
            Width = 360;
            Title = row == null ? "Add Images" : "Edit Images";
            var root = new StackPanel { Margin = new Thickness(12), Spacing = 8 };
        root.Children.Add(new TextBlock { Text = "ID" });
        idInput = new NumericUpDown { Minimum = 0, Increment = 1 };
        root.Children.Add(idInput);
        root.Children.Add(new TextBlock { Text = "Image" });
        imageInput = new TextBox();
        var row_imageInput = new Grid();
        row_imageInput.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));
        row_imageInput.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Auto));
        row_imageInput.Children.Add(imageInput);
        var browse_imageInput = new Button { Content = "Browse…" };
        browse_imageInput.Margin = new Thickness(6, 0, 0, 0);
        browse_imageInput.Click += async (_, _) => await BrowseAsync(imageInput);
        Grid.SetColumn(browse_imageInput, 1);
        row_imageInput.Children.Add(browse_imageInput);
        root.Children.Add(row_imageInput);
        root.Children.Add(new TextBlock { Text = "File" });
        fileInput = new TextBox();
        var row_fileInput = new Grid();
        row_fileInput.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));
        row_fileInput.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Auto));
        row_fileInput.Children.Add(fileInput);
        var browse_fileInput = new Button { Content = "Browse…" };
        browse_fileInput.Margin = new Thickness(6, 0, 0, 0);
        browse_fileInput.Click += async (_, _) => await BrowseAsync(fileInput);
        Grid.SetColumn(browse_fileInput, 1);
        row_fileInput.Children.Add(browse_fileInput);
        root.Children.Add(row_fileInput);
            var btnRow = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8, HorizontalAlignment = HorizontalAlignment.Right };
            var saveBtn = new Button { Content = "Save", IsDefault = true };
            saveBtn.Click += (_, _) => Close(true);
            var cancelBtn = new Button { Content = "Cancel", IsCancel = true };
            cancelBtn.Click += (_, _) => Close();
            btnRow.Children.Add(saveBtn);
            btnRow.Children.Add(cancelBtn);
            root.Children.Add(btnRow);
            Content = root;
            if (row != null) LoadRow(row);
            else if (newKey.HasValue) { idInput.Value = newKey.Value; idInput.IsReadOnly = true; }
        }

        private void LoadRow(ImagesRow row)
        {
        idInput.Value = row.Id;
        imageInput.Text = row.Image;
        fileInput.Text = row.File;
        }

        public ImagesRow NewRow()
        {
            var row = new ImagesRow();
            ApplyTo(row);
            return row;
        }

        public void ApplyTo(ImagesRow row)
        {
        row.Id = (int)Math.Truncate(idInput.Value.GetValueOrDefault());
        row.Image = imageInput.Text;
        row.File = fileInput.Text;
        }

        private async Task BrowseAsync(TextBox box)
        {
            var options = new FilePickerOpenOptions
            {
                Title = "Select a file",
                AllowMultiple = false,
                FileTypeFilter = new[] { FilePickerFileTypes.ImageAll, FilePickerFileTypes.All }
            };
            var last = FilePickerMemory.LastFolder;
            if (!string.IsNullOrEmpty(last))
            {
                try { options.SuggestedStartLocation = await StorageProvider.TryGetFolderFromPathAsync(new Uri(last)); }
                catch { /* the remembered folder is gone - let the OS choose */ }
            }
            var files = await StorageProvider.OpenFilePickerAsync(options);
            if (files.Count == 0) return;
            var path = files[0].TryGetLocalPath();
            if (string.IsNullOrEmpty(path)) return;
            box.Text = path;
            try { FilePickerMemory.LastFolder = Path.GetDirectoryName(path); } catch { /* best effort */ }
        }
    }

    public class ConfirmDialog : Window
    {
        public ConfirmDialog(string title, string message)
        {
            Title = title;
            Width = 320;
            var root = new StackPanel { Margin = new Thickness(12), Spacing = 12 };
            root.Children.Add(new TextBlock { Text = message, TextWrapping = Avalonia.Media.TextWrapping.Wrap });
            var btnRow = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8, HorizontalAlignment = HorizontalAlignment.Right };
            var yesBtn = new Button { Content = "Yes", IsDefault = true };
            yesBtn.Click += (_, _) => Close(true);
            var noBtn = new Button { Content = "No", IsCancel = true };
            noBtn.Click += (_, _) => Close();
            btnRow.Children.Add(yesBtn);
            btnRow.Children.Add(noBtn);
            root.Children.Add(btnRow);
            Content = root;
        }
    }

    public class DateTimeToOffsetConverter : Avalonia.Data.Converters.IValueConverter
    {
        public object? Convert(object? value, Type targetType, object? parameter, System.Globalization.CultureInfo culture)
        {
            if (value is DateTime dt && dt != DateTime.MinValue) return new DateTimeOffset(DateTime.SpecifyKind(dt, DateTimeKind.Local));
            return null;
        }
        public object? ConvertBack(object? value, Type targetType, object? parameter, System.Globalization.CultureInfo culture)
        {
            if (value is DateTimeOffset dto) return dto.LocalDateTime;
            return null;
        }
    }
}
