// Avalonia.Headless runtime driver — generated by tests/t4-runtime/headless.test.js.
// Builds the USER's generated project (via ProjectReference), instantiates its real
// MainWindow and drives it on the headless platform, printing one "PASS/FAIL name" line
// per check and a final "RESULT PASS|FAIL". Exit code 0 = all checks passed.
//
// {NAMESPACE} is substituted with the generated project's root namespace.
using System;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Threading;
using {NAMESPACE};

internal static class Program
{
    private static int _fails;

    private static void Check(bool cond, string name, string detail = "")
    {
        Console.WriteLine((cond ? "PASS " : "FAIL ") + name + (detail.Length > 0 ? " " + detail : ""));
        if (!cond) _fails++;
    }

    private static void Layout(Window w)
    {
        w.Measure(Size.Infinity);
        w.Arrange(new Rect(0, 0, w.ClientSize.Width, w.ClientSize.Height));
        Dispatcher.UIThread.RunJobs();
    }

    [STAThread]
    public static int Main()
    {
        try
        {
            AppBuilder.Configure<App>()
                .UseHeadless(new AvaloniaHeadlessPlatformOptions())
                .UseSkia()
                .SetupWithoutStarting();

            var window = new MainWindow();
            window.Show();
            Layout(window);

            Check(window is MainWindow, "window-created", window.GetType().Name);

            var body = window.FindControl<Canvas>("Body");
            Check(body != null, "body-found", body == null ? "no Body canvas" : "");

            if (body != null)
            {
                double cw = window.ClientSize.Width, ch = window.ClientSize.Height;
                Layout(window);
                cw = window.ClientSize.Width; ch = window.ClientSize.Height;
                Check(Math.Abs(body.Bounds.Width - cw) < 2, "body-fills-width", $"body={body.Bounds.Width:F1} client={cw:F1}");
                Check(Math.Abs(body.Bounds.Height - ch) < 2, "body-fills-height", $"body={body.Bounds.Height:F1} client={ch:F1}");
            }

            // Resize the window: the Body canvas must follow the new client size.
            window.Width = 1024;
            window.Height = 640;
            Layout(window);
            if (body != null)
            {
                double cw = window.ClientSize.Width, ch = window.ClientSize.Height;
                Check(Math.Abs(body.Bounds.Width - cw) < 3, "body-resize-width", $"body={body.Bounds.Width:F1} client={cw:F1}");
                Check(Math.Abs(body.Bounds.Height - ch) < 3, "body-resize-height", $"body={body.Bounds.Height:F1} client={ch:F1}");
            }

            // Window-state transitions.
            window.WindowState = WindowState.Maximized; Dispatcher.UIThread.RunJobs();
            Check(window.WindowState == WindowState.Maximized, "maximized", window.WindowState.ToString());
            window.WindowState = WindowState.Minimized; Dispatcher.UIThread.RunJobs();
            Check(window.WindowState == WindowState.Minimized, "minimized", window.WindowState.ToString());
            window.WindowState = WindowState.Normal; Dispatcher.UIThread.RunJobs();
            Check(window.WindowState == WindowState.Normal, "normal", window.WindowState.ToString());

            // A control placed at (100,50) 120x36 keeps its design position + size.
            var button = window.FindControl<Button>("btnTest");
            if (button != null)
            {
                Layout(window);
                Check(Math.Abs(button.Bounds.X - 100) < 2, "control-x", $"{button.Bounds.X:F1}");
                Check(Math.Abs(button.Bounds.Y - 50) < 2, "control-y", $"{button.Bounds.Y:F1}");
                Check(Math.Abs(button.Bounds.Width - 120) < 2, "control-width", $"{button.Bounds.Width:F1}");
            }
            else
            {
                Check(false, "control-found", "btnTest missing");
            }

            Console.WriteLine("RESULT " + (_fails == 0 ? "PASS" : "FAIL"));
            window.Close();
            return _fails == 0 ? 0 : 1;
        }
        catch (Exception ex)
        {
            Console.WriteLine("RESULT FAIL");
            Console.WriteLine("EXCEPTION " + ex);
            return 1;
        }
    }
}
