// Headless driver for the chart's FILL / RESTORE ("dock" and "undock") — generated by
// tests/t4-runtime/chartFill.test.js. Compiles the extension's own resources/GrumpyCharts.cs, builds a
// real Avalonia 12.1.1 window around a chart and MEASURES the geometry:
//   - the fill really takes the container's rectangle (a Canvas child, and a Grid child spanning the grid),
//   - the restore puts back the exact original placement (position, size, canvas/grid attachments, Z),
//   - Esc restores a filled chart through the real key route, and is NOT swallowed when the chart is
//     collapsed (a dialog around it keeps its own Esc),
//   - a filled chart keeps up with its container when the window is resized.
// Prints one "PASS/FAIL name" line per check and a final "RESULT PASS|FAIL". Exit code 0 = all passed.
using System;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Input;
using Avalonia.Threading;
using AvaloniaCharts;

internal static class Program
{
    private static int _fails;

    private static void Check(bool cond, string name, string detail = "")
    {
        Console.WriteLine((cond ? "PASS " : "FAIL ") + name + (detail.Length > 0 ? " " + detail : ""));
        if (!cond) _fails++;
    }

    private static void Layout(Window w)
    {
        w.Measure(Size.Infinity);
        w.Arrange(new Rect(0, 0, w.ClientSize.Width, w.ClientSize.Height));
        Dispatcher.UIThread.RunJobs();
    }

    [STAThread]
    public static int Main()
    {
        try
        {
            AppBuilder.Configure<Application>()
                .UseHeadless(new AvaloniaHeadlessPlatformOptions())
                .UseSkia()
                .SetupWithoutStarting();

            // ================= a chart in a CANVAS — the designer's own body =================
            var chart = new GrumpyLinePlot { Width = 160, Height = 90, Values = new double[] { 1, 4, 2, 5, 3 } };
            Canvas.SetLeft(chart, 20);
            Canvas.SetTop(chart, 30);
            // The Canvas has no size of its own (that is how the designer's Body behaves): it is stretched by
            // the Grid around it, so the CONTAINER follows the window and the fill has something to track.
            var body = new Canvas();
            body.Children.Add(chart);
            var root = new Grid();
            root.Children.Add(body);
            var window = new Window { Width = 400, Height = 300, Content = root };
            window.Show();
            Layout(window);

            Check(Math.Abs(chart.Bounds.X - 20) < 2 && Math.Abs(chart.Bounds.Y - 30) < 2, "start-position",
                $"at {chart.Bounds.X:F1},{chart.Bounds.Y:F1}");
            Check(Math.Abs(chart.Bounds.Width - 160) < 2 && Math.Abs(chart.Bounds.Height - 90) < 2, "start-size",
                $"{chart.Bounds.Width:F1}x{chart.Bounds.Height:F1}");
            Check(!chart.IsFilled, "start-not-filled");

            Check(chart.FillContainer(), "fill-returns-true");
            Layout(window);
            Check(chart.IsFilled, "fill-flag");
            Check(Math.Abs(chart.Bounds.Width - body.Bounds.Width) < 2, "fill-width",
                $"chart={chart.Bounds.Width:F1} container={body.Bounds.Width:F1}");
            Check(Math.Abs(chart.Bounds.Height - body.Bounds.Height) < 2, "fill-height",
                $"chart={chart.Bounds.Height:F1} container={body.Bounds.Height:F1}");
            Check(Math.Abs(chart.Bounds.X) < 2 && Math.Abs(chart.Bounds.Y) < 2, "fill-at-corner",
                $"at {chart.Bounds.X:F1},{chart.Bounds.Y:F1}");
            Check(chart.ZIndex >= 1000, "fill-on-top", "z=" + chart.ZIndex);
            Check(!chart.FillContainer(), "fill-twice-false");

            // The point of docking it: it must still fit when the window grows.
            window.Width = 600;
            window.Height = 420;
            Layout(window);
            Check(chart.Bounds.Width > 400, "fill-grew", $"{chart.Bounds.Width:F1}");
            Check(Math.Abs(chart.Bounds.Width - body.Bounds.Width) < 3, "fill-follows-resize",
                $"chart={chart.Bounds.Width:F1} container={body.Bounds.Width:F1}");
            Check(Math.Abs(chart.Bounds.Height - body.Bounds.Height) < 3, "fill-follows-resize-height",
                $"chart={chart.Bounds.Height:F1} container={body.Bounds.Height:F1}");

            // ================= the restore is exact =================
            Check(chart.RestorePlacement(), "restore-returns-true");
            Layout(window);
            Check(!chart.IsFilled, "restore-flag");
            Check(Math.Abs(chart.Bounds.X - 20) < 2 && Math.Abs(chart.Bounds.Y - 30) < 2, "restore-position",
                $"at {chart.Bounds.X:F1},{chart.Bounds.Y:F1}");
            Check(Math.Abs(chart.Bounds.Width - 160) < 2 && Math.Abs(chart.Bounds.Height - 90) < 2, "restore-size",
                $"{chart.Bounds.Width:F1}x{chart.Bounds.Height:F1}");
            Check(Math.Abs(Canvas.GetLeft(chart) - 20) < 0.01 && Math.Abs(Canvas.GetTop(chart) - 30) < 0.01,
                "restore-canvas-attached", $"left={Canvas.GetLeft(chart):F1} top={Canvas.GetTop(chart):F1}");
            Check(chart.ZIndex == 0, "restore-z", "z=" + chart.ZIndex);
            Check(!chart.RestorePlacement(), "restore-twice-false");

            // ================= Esc =================
            var escape = new KeyEventArgs { RoutedEvent = InputElement.KeyDownEvent, Key = Key.Escape };
            chart.RaiseEvent(escape);
            Check(!escape.Handled, "esc-ignored-when-collapsed");

            chart.FillContainer();
            Layout(window);
            Check(chart.IsFilled, "fill-again");
            chart.Focus();
            window.KeyPressQwerty(PhysicalKey.Escape, RawInputModifiers.None);
            Layout(window);
            Check(!chart.IsFilled, "esc-restores", chart.IsFilled ? "still filled" : "");
            Check(Math.Abs(chart.Bounds.Width - 160) < 2 && Math.Abs(chart.Bounds.X - 20) < 2, "esc-restores-exactly",
                $"{chart.Bounds.X:F1},{chart.Bounds.Y:F1} {chart.Bounds.Width:F1}x{chart.Bounds.Height:F1}");

            // …and the handler marks it handled while filled (so a menu/dialog does not also act on it).
            chart.FillContainer();
            Layout(window);
            var escape2 = new KeyEventArgs { RoutedEvent = InputElement.KeyDownEvent, Key = Key.Escape };
            chart.RaiseEvent(escape2);
            Layout(window);
            Check(escape2.Handled && !chart.IsFilled, "esc-handled-while-filled");

            // ================= a chart in a GRID cell: the fill spans the grid =================
            var grid = new Grid
            {
                Width = 400,
                Height = 300,
                RowDefinitions = new RowDefinitions("*,*"),
                ColumnDefinitions = new ColumnDefinitions("*,*")
            };
            var inGrid = new GrumpyBarPlot { Width = 120, Height = 80, Values = new double[] { 3, 6, 4 } };
            Grid.SetRow(inGrid, 1);
            Grid.SetColumn(inGrid, 1);
            grid.Children.Add(inGrid);
            var gridRoot = new Grid();
            gridRoot.Children.Add(grid);
            var window2 = new Window { Width = 400, Height = 300, Content = gridRoot };
            window2.Show();
            Layout(window2);

            Check(inGrid.FillContainer(), "grid-fill-returns-true");
            Layout(window2);
            Check(Math.Abs(inGrid.Bounds.Width - grid.Bounds.Width) < 2, "grid-fill-spans-width",
                $"chart={inGrid.Bounds.Width:F1} grid={grid.Bounds.Width:F1}");
            Check(Math.Abs(inGrid.Bounds.Height - grid.Bounds.Height) < 2, "grid-fill-spans-height",
                $"chart={inGrid.Bounds.Height:F1} grid={grid.Bounds.Height:F1}");
            Check(Grid.GetRowSpan(inGrid) == 2 && Grid.GetColumnSpan(inGrid) == 2, "grid-fill-spans-cells",
                $"span={Grid.GetRowSpan(inGrid)}x{Grid.GetColumnSpan(inGrid)}");

            Check(inGrid.RestorePlacement(), "grid-restore-returns-true");
            Layout(window2);
            Check(Grid.GetRow(inGrid) == 1 && Grid.GetColumn(inGrid) == 1 && Grid.GetRowSpan(inGrid) == 1
                && Grid.GetColumnSpan(inGrid) == 1, "grid-restore-cell",
                $"at {Grid.GetRow(inGrid)},{Grid.GetColumn(inGrid)} span={Grid.GetRowSpan(inGrid)}x{Grid.GetColumnSpan(inGrid)}");
            Check(Math.Abs(inGrid.Bounds.Width - 120) < 2 && Math.Abs(inGrid.Bounds.Height - 80) < 2,
                "grid-restore-size", $"{inGrid.Bounds.Width:F1}x{inGrid.Bounds.Height:F1}");

            // ================= every chart type carries the entry =================
            // The menu is built by the base class, so this is a smoke check that each of the six types
            // really is a ChartBase (and therefore really offers Fill / Restore).
            var types = new ChartBase[]
            {
                new GrumpyLinePlot(), new GrumpyXYPlot(), new GrumpyBarPlot(), new GrumpyAreaPlot(),
                new GrumpyPiePlot(), new GrumpyWaterfallPlot()
            };
            var allFill = true;
            foreach (var one in types)
            {
                var host = new Canvas();
                host.Children.Add(one);
                var holder = new Grid();
                holder.Children.Add(host);
                var w = new Window { Width = 300, Height = 200, Content = holder };
                w.Show();
                Layout(w);
                if (!one.FillContainer()) allFill = false;
                Layout(w);
                if (Math.Abs(one.Bounds.Width - host.Bounds.Width) > 2) allFill = false;
                if (!one.RestorePlacement()) allFill = false;
                w.Close();
            }
            Check(allFill, "every-chart-type-fills-and-restores", "six types");

            Console.WriteLine("RESULT " + (_fails == 0 ? "PASS" : "FAIL"));
            window.Close();
            return _fails == 0 ? 0 : 1;
        }
        catch (Exception ex)
        {
            Console.WriteLine("RESULT FAIL");
            Console.WriteLine("EXCEPTION " + ex);
            return 1;
        }
    }
}
