// Headless driver for the chart's HARDCOPY paths — generated by tests/t4-runtime/printExport.test.js.
// Compiles the extension's own resources/GrumpyCharts.cs AND resources/GrumpyPrint.cs with
// PRINT_SUPPORT and the two real printer packages, then exercises what only a running app can show:
//   - what "can this machine print?" means: Avae.Printables' own service (never registered here — the
//     harness deliberately does not call UsePrintables()) or a CUPS client the bundled helper drives,
//   - the picker-free PDF export writes a real PDF, for the chart's own size AND for A4,
//   - the PNG export writes a picture, and the Print* rows (paper, margin, white page) drive it,
//   - a failing export reports through PrintFailed instead of throwing, and returns false,
//   - a chart with no window refuses (the designer preview's case) and does NOT report a failure,
//   - and PRINTING itself: the page is rendered and handed to `lp` with the job title, the temporary
//     file is cleaned up, and with no CUPS client at all the entry refuses and says so.
//
// The PATH decides which of the last two the run sees — the node side puts either a STUB `lp`
// (mode cups) or an empty folder (mode nocups) in front of it — so the checks are the same on a
// machine with printers and on one without CUPS. The CUPS answer is cached on first look, so the PATH
// must be installed before anything asks for it; that is the first thing Main does.
//
// The page geometry, the pixels and the recorded `lp` command line are MEASURED by the node side,
// from the artefacts written here. Prints "PASS/FAIL name" lines and a final RESULT; exit 0 = passed.
using System;
using System.IO;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Media;
using Avalonia.Threading;
using AvaloniaCharts;
using Avae.Printables;

internal static class Program
{
    private static int _fails;

    private static void Check(bool cond, string name, string detail = "")
    {
        Console.WriteLine((cond ? "PASS " : "FAIL ") + name + (detail.Length > 0 ? " " + detail : ""));
        if (!cond) _fails++;
    }

    private static void Layout(Window w)
    {
        w.Measure(Size.Infinity);
        w.Arrange(new Rect(0, 0, w.ClientSize.Width, w.ClientSize.Height));
        Dispatcher.UIThread.RunJobs();
    }

    /// <summary>Is there really no Avae.Printables service? (Its getter may throw in the API-only build,
    /// which is exactly the "no service" answer.)</summary>
    private static bool NoAvaeService()
    {
        try { return Printable.Default is null; } catch { return true; }
    }

    /// <summary>A shown window with one line chart in it, laid out — the harness's subject.</summary>
    private static (GrumpyLinePlot, Window) ShowChart(string name)
    {
        var chart = new GrumpyLinePlot
        {
            Name = name,
            Width = 400,
            Height = 200,
            Values = new double[] { 1, 4, 2, 5, 3, 6 },
            LineColor = Color.Parse("#1E88E5")
        };
        // …and a NAMED series beside the bare Values line. Without one the chart has nothing the legend
        // could list — MeasureLegend: "a chart without series elements draws one unnamed line, and there is
        // nothing to name or switch off" — so the Print Legend row would have nothing to show either way.
        chart.Series.Add(new LineSeries { Title = "Sales" });
        var window = new Window { Width = 600, Height = 400, Content = chart };
        window.Show();
        Layout(window);
        return (chart, window);
    }

    [STAThread]
    public static int Main(string[] args)
    {
        var dir = args.Length > 0 ? args[0] : Path.Combine(Path.GetTempPath(), "grumpy-print-harness");
        var mode = args.Length > 1 ? args[1] : "nocups";
        var pathDir = args.Length > 2 ? args[2] : "";
        Directory.CreateDirectory(dir);
        Console.WriteLine("ARTEFACT DIR " + dir);
        Console.WriteLine("MODE " + mode);
        try
        {
            // BEFORE anything looks at the printer: which CUPS client this run finds (the stub, or none).
            if (pathDir.Length > 0)
            {
                // cups mode: the stub goes IN FRONT of the real PATH, so it wins over any installed lp.
                // nocups mode: that folder IS the whole PATH, so no lp can be found anywhere — which is how
                // these checks read the same on a machine with printers and on one without CUPS at all (the
                // node side hands us an empty folder for it).
                var wanted = mode == "cups"
                    ? pathDir + Path.PathSeparator + Environment.GetEnvironmentVariable("PATH")
                    : pathDir;
                Environment.SetEnvironmentVariable("PATH", wanted);
                // The stub script records its command line and keeps the file it was handed.
                Environment.SetEnvironmentVariable("GRUMPY_STUB_DIR", pathDir);
            }

            AppBuilder.Configure<Application>()
                .UseHeadless(new AvaloniaHeadlessPlatformOptions())
                .UseSkia()
                .SetupWithoutStarting();

            Check(NoAvaeService(), "no-avae-service", "Printable.Default is null (UsePrintables() never called)");

            if (mode == "cups") RunCups(dir);
            else RunNoCups();

            Console.WriteLine("RESULT " + (_fails == 0 ? "PASS" : "FAIL"));
            return _fails == 0 ? 0 : 1;
        }
        catch (Exception error)
        {
            Console.WriteLine("FAIL harness-threw " + error);
            Console.WriteLine("RESULT FAIL");
            return 1;
        }
    }

    /// <summary>Mode `cups`: a stub `lp` is on the PATH, so this machine CAN print — through CUPS.</summary>
    private static void RunCups(string dir)
    {
        Check(GrumpyPrint.Available, "cups-available-with-lp-on-path", "the stub lp was found on PATH");
        Check(ChartBase.CanPrint, "canprint-true-with-cups", "a CUPS client is enough — no UsePrintables()");

        var (chart, window) = ShowChart("Harness chart");
        var failures = 0;
        chart.PrintFailed += (_, e) =>
        {
            failures++;
            Console.WriteLine("NOTE printfailure " + e.GetType().Name + ": " + e.Message);
        };

        // ---------- the PRINT LEGEND row: Off drops the legend from the page, On forces it on, and ----------
        // ---------- NEITHER ever changes the chart on screen (the node side measures the pictures) ----------
        var legendDrawn = Path.Combine(dir, "legend-drawn.png");
        var legendOff = Path.Combine(dir, "legend-off.png");
        var legendForced = Path.Combine(dir, "legend-forced.png");
        chart.ShowLegend = true;
        Check(chart.ExportPng(legendDrawn, 1), "exportpng-legend-drawn-true");
        chart.PrintLegend = ChartLegendMode.Off;
        Check(chart.ExportPng(legendOff, 1), "exportpng-legend-off-true");
        Check(chart.ShowLegend, "legend-off-leaves-the-screen-alone",
            "the chart still shows its own legend after an export was told to leave it off the page");
        chart.PrintLegend = ChartLegendMode.On;
        chart.ShowLegend = false;
        Check(chart.ExportPng(legendForced, 1), "exportpng-legend-forced-true");
        Check(chart.ShowLegend == false, "legend-on-leaves-the-screen-alone",
            "and forcing it ON for the page did not switch the chart's own legend on either");
        chart.PrintLegend = ChartLegendMode.AsDrawn;
        chart.ShowLegend = true;

        // ---------- the PRINT INK row: Mono takes the PLOT BACKGROUND off the page — and puts it back ----------
        // The plate is a colour the chart draws nowhere else, so the node side can count it: it must be all
        // over the colour page and absent from the mono one, while the graph itself stays in both.
        var inkPlate = new SolidColorBrush(Color.Parse("#123456"));
        chart.PlotBackBrush = inkPlate;
        chart.PlotBackOpacity = 100;
        var inkColour = Path.Combine(dir, "ink-colour.png");
        var inkMono = Path.Combine(dir, "ink-mono.png");
        Check(chart.ExportPng(inkColour, 1), "exportpng-ink-colour-true");
        chart.PrintInk = ChartInkMode.Mono;
        Check(chart.ExportPng(inkMono, 1), "exportpng-ink-mono-true");
        Check(ReferenceEquals(chart.PlotBackBrush, inkPlate), "ink-mono-leaves-the-brush-alone",
            "the plot background brush is the form's own again after the job");
        Check(Math.Abs(chart.PlotBackOpacity - 100) < 0.001, "ink-mono-leaves-the-opacity-alone",
            $"PlotBackOpacity={chart.PlotBackOpacity}");
        chart.PrintInk = ChartInkMode.Colour;
        chart.PlotBackBrush = null;
        chart.PlotBackOpacity = 100;

        // ---------- PDF: the chart's own page, and A4 ----------
        var pdfDrawn = Path.Combine(dir, "asdrawn.pdf");
        var pdfA4 = Path.Combine(dir, "a4.pdf");
        Check(chart.ExportPdfAsync(pdfDrawn).GetAwaiter().GetResult(), "exportpdf-asdrawn-true");
        Check(chart.ExportPdfAsync(pdfA4, ChartPrintOptions.A4).GetAwaiter().GetResult(),
            "exportpdf-a4-true");
        Check(File.Exists(pdfDrawn) && File.Exists(pdfA4), "pdf-files-exist");
        Check(new FileInfo(pdfDrawn).Length > 1000 && new FileInfo(pdfA4).Length > 1000,
            "pdf-not-empty", $"{new FileInfo(pdfDrawn).Length}/{new FileInfo(pdfA4).Length} bytes");
        Check(File.ReadAllText(pdfDrawn).StartsWith("%PDF"), "pdf-header", "starts with %PDF");

        // ---------- PNG: the chart's own size, then an A4 page with a white background ----------
        var pngDrawn = Path.Combine(dir, "asdrawn.png");
        var pngA4 = Path.Combine(dir, "a4.png");
        Check(chart.ExportPng(pngDrawn, 1), "exportpng-asdrawn-true");

        chart.PrintPaper = ChartPaper.A4;
        chart.PrintLightBackground = true;
        chart.PrintMargin = 24;
        Check(chart.PrintPaper == ChartPaper.A4, "properties-roundtrip-paper");
        Check(Math.Abs(chart.PrintMargin - 24) < 0.001, "properties-roundtrip-margin");
        Check(chart.PrintLightBackground, "properties-roundtrip-light");
        Check(chart.ExportPng(pngA4, 1), "exportpng-a4-true");

        // ---------- a failure is reported, not thrown ----------
        var bad = Path.Combine(dir, "no-such-directory", "x.pdf");
        Check(!chart.ExportPdfAsync(bad).GetAwaiter().GetResult(), "failed-export-returns-false");
        Check(failures == 1, "printfailed-raised-once", $"failures={failures}");

        // ---------- PRINTING: the page is rendered to a PDF and handed to `lp` ----------
        // Back to the chart's own size, so the node side can check that the page it received is a real
        // 400 x 200 PDF with the chart on it — and that the stub was asked to print *that* file.
        chart.PrintPaper = ChartPaper.AsDrawn;
        Check(chart.PrintAsync().GetAwaiter().GetResult(), "print-with-cups-true");
        Check(failures == 1, "cups-print-is-not-a-failure", $"failures={failures}");
        Check(!chart.IsPrinting, "not-printing-after-the-run");
        window.Close();
    }

    /// <summary>Mode `nocups`: nothing on this machine can print, so the entry must refuse honestly.</summary>
    private static void RunNoCups()
    {
        Check(!GrumpyPrint.Available, "cups-unavailable-without-lp", "no lp on PATH");
        Check(!ChartBase.CanPrint, "canprint-false-without-service", "no service and no CUPS client");

        var (chart, window) = ShowChart("Harness chart");
        var failures = 0;
        chart.PrintFailed += (_, e) =>
        {
            failures++;
            Console.WriteLine("NOTE printfailure " + e.GetType().Name + ": " + e.Message);
        };

        Check(!chart.PrintAsync().GetAwaiter().GetResult(), "print-without-service-false");
        Check(failures == 1, "printfailed-raised-for-missing-service", $"failures={failures}");
        Check(!chart.IsPrinting, "not-printing-after-the-run");

        // ---------- a detached chart (no window) refuses quietly ----------
        // The designer preview's case: no TopLevel is a state, not a printer failure — so it must NOT
        // report one (the count above stands at 1).
        var detached = new GrumpyLinePlot { Width = 100, Height = 50, Values = new double[] { 1, 2 } };
        Check(!detached.PrintAsync().GetAwaiter().GetResult(), "print-without-window-false");
        Check(failures == 1, "no-window-is-not-a-failure-report", $"failures={failures}");
        window.Close();
    }
}
