/* T4 — the Timer component, RUNNING. The WinForms-Timer promise is about threads, and only a running
 * app can show it: this generates a real C# project, drops a `<chrome:Timer Interval="40" Enabled="True"/>`
 * into its form, then drives its real MainWindow on the headless platform and asserts that
 *
 *   - the component is in the form and takes no space (0x0) — it is a component, not a control;
 *   - it TICKS (>= 2 times in half a second at Interval=40 — "it is a timer");
 *   - every tick arrives on a NON-UI thread (the user's requirement: "the timer must run in a worker
 *     thread", so a slow handler cannot freeze the window);
 *   - no Tick attribute is needed in the form, because the harness subscribes to the real event;
 *   - closing the window STOPS it — a pool thread must not keep calling into a dead form.
 *
 * The project being driven also proves the bundled twins build: `Timer.cs` is a scaffold file, so the
 * build of this app compiles it, and the T5 VB matrix compiles the .vb twin.
 *
 * This layer is the SLOWEST (a net10 build + restore) — run it on demand via `npm run test:runtime`.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { generateProject, OUT_DIR } = require('../helpers/build');

const DIR = path.join(__dirname, '..', 'out', 'timer');
const HARNESS_DIR = path.join(DIR, 'Harness');
const APP = 'TimerApp';

const CSPROJ = `<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>TimerHarness</AssemblyName>
    <RootNamespace>TimerHarness</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="12.1.1" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\projects\\${APP}\\${APP}.csproj" />
  </ItemGroup>
</Project>
`;

/** The driver: it watches the REAL event of the component the form carries. */
const PROGRAM = `// Generated by tests/t4-runtime/timer.test.js — drives a real app that holds a <chrome:Timer>.
using System;
using System.Collections.Generic;
using System.Threading;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Threading;
using {NAMESPACE};

internal static class Program
{
    private static int _fails;
    private static int _ticks;
    private static readonly List<int> Threads = new List<int>();

    private static void Check(bool cond, string name, string detail = "")
    {
        Console.WriteLine((cond ? "PASS " : "FAIL ") + name + (detail.Length > 0 ? " " + detail : ""));
        if (!cond) _fails++;
    }

    private static void Layout(Window w)
    {
        w.Measure(Size.Infinity);
        w.Arrange(new Rect(0, 0, w.ClientSize.Width, w.ClientSize.Height));
        Dispatcher.UIThread.RunJobs();
    }

    [STAThread]
    public static int Main()
    {
        try
        {
            AppBuilder.Configure<App>()
                .UseHeadless(new AvaloniaHeadlessPlatformOptions())
                .UseSkia()
                .SetupWithoutStarting();

            var window = new MainWindow();
            window.Show();
            Layout(window);

            var timer = window.FindControl<AvaloniaChrome.Timer>("timerTest");
            Check(timer != null, "timer-found", timer == null ? "no timerTest in the form" : "");
            if (timer == null) { Console.WriteLine("RESULT FAIL"); return 1; }

            Check(!timer.IsVisible, "component-invisible", "IsVisible=" + timer.IsVisible);
            Layout(window);
            Check(timer.Bounds.Width == 0 && timer.Bounds.Height == 0, "component-takes-no-space",
                $"bounds={timer.Bounds.Width:F0}x{timer.Bounds.Height:F0}");
            Check(timer.Enabled, "started-from-xaml", "Enabled=" + timer.Enabled);
            Check(Math.Abs(timer.Interval - 40) < 0.001, "interval-from-xaml", "Interval=" + timer.Interval);

            int uiThread = Environment.CurrentManagedThreadId;
            timer.Tick += (_, _) =>
            {
                Interlocked.Increment(ref _ticks);
                lock (Threads) { if (!Threads.Contains(Environment.CurrentManagedThreadId)) Threads.Add(Environment.CurrentManagedThreadId); }
            };

            // The XAML-bound handler must have fired too: that binding (Tick="timerTest_Tick" with the
            // component's own EventHandler signature) is what the designer generates, and a signature
            // mismatch there is a BUILD error the language server never shows.
            Check(MainWindow.TickCount > 0, "xaml-bound-handler-ran",
                "MainWindow.TickCount=" + MainWindow.TickCount);

            // The worker timer fires on its own; the UI thread only idles here.
            Thread.Sleep(500);
            Dispatcher.UIThread.RunJobs();

            int first = Volatile.Read(ref _ticks);
            Check(first >= 2, "ticks", $"ticks={first} in 500 ms at Interval=40");
            lock (Threads)
            {
                Check(Threads.Count > 0, "ticks-on-a-worker-thread", "threads seen: " + Threads.Count);
                Check(!Threads.Contains(uiThread), "not-the-ui-thread",
                    $"ui={uiThread} tick={string.Join(",", Threads)}");
            }

            // Stop it from code, exactly as a form does when the job is done.
            timer.Stop();
            Thread.Sleep(120);
            int stopped = Volatile.Read(ref _ticks);
            Thread.Sleep(200);
            Check(Volatile.Read(ref _ticks) == stopped, "stop-stops-it", $"ticks stayed at {stopped}");

            timer.Start();
            Thread.Sleep(160);
            Check(Volatile.Read(ref _ticks) > stopped, "start-starts-it-again",
                $"{stopped} -> {Volatile.Read(ref _ticks)}");

            // …and the form going away must silence it, or a pool thread would keep calling into a dead
            // window (the failure this component's detach handling exists to prevent).
            window.Close();
            Thread.Sleep(60);
            int atClose = Volatile.Read(ref _ticks);
            Thread.Sleep(250);
            Check(Volatile.Read(ref _ticks) == atClose, "close-stops-it", $"ticks stayed at {atClose}");
        }
        catch (Exception ex)
        {
            Console.WriteLine("FAIL harness " + ex.Message);
            _fails++;
        }
        Console.WriteLine(_fails == 0 ? "RESULT PASS" : "RESULT FAIL");
        return _fails == 0 ? 0 : 1;
    }
}
`;

module.exports = async (t) => {
    t.section('T4: the Timer component running (worker thread)');

    // 1) a real generated C# project, with the component dropped into its form
    t.note('generating ' + APP + ' (C# blank)…');
    const dir = generateProject({ language: 'cs', tplId: 'blank', name: APP });
    const axamlPath = path.join(dir, 'MainWindow.axaml');
    let axaml = fs.readFileSync(axamlPath, 'utf8');
    t.ok(axaml.includes('Timer.cs') === false && fs.existsSync(path.join(dir, 'Timer.cs')), 'scaffold',
        'the generated project carries the bundled Timer.cs');
    if (!axaml.includes('x:Name="timerTest"')) {
        // A form that carries a `chrome:` element must declare the namespace, which is what the
        // designer's model does for every bundled snippet it drops (XamlModel.addControl). The blank
        // template's root is a plain Window, so the declaration is added here the same way.
        if (!axaml.includes('xmlns:chrome=')) {
            axaml = axaml.replace('<Window xmlns="https://github.com/avaloniaui"',
                '<Window xmlns="https://github.com/avaloniaui"\n        xmlns:chrome="using:AvaloniaChrome"');
        }
        // The event attribute is part of the test on purpose (2026-09-29): the compiled XAML must
        // ATTACH a handler with the component's own `EventHandler` signature, and that is the half no
        // earlier test covered. A stub generated with `RoutedEventArgs` compiled cleanly in the
        // language server and then failed the real build with AVLN3000 — it took the user's app down.
        axaml = axaml.replace('<Canvas Name="Body">',
            '<Canvas Name="Body">\n            <chrome:Timer x:Name="timerTest" Interval="40" Enabled="True" Tick="timerTest_Tick"/>');
        fs.writeFileSync(axamlPath, axaml, 'utf8');
        // …and the handler the attribute names, with the signature the component declares.
        const csPath = path.join(dir, 'MainWindow.axaml.cs');
        let cs = fs.readFileSync(csPath, 'utf8');
        const handler = '\n    public static int TickCount;\n' +
            '    private void timerTest_Tick(object? sender, System.EventArgs e)\n    {\n' +
            '        TickCount++;\n    }\n';
        cs = cs.replace(/\n}\s*$/, handler + '}\n');
        fs.writeFileSync(csPath, cs, 'utf8');
    }
    t.ok(axaml.includes('Tick="timerTest_Tick"'), 'scaffold',
        'the form wires Tick in XAML (the compiled binding is part of what this test proves)');

    // 2) the harness that drives that window
    fs.rmSync(HARNESS_DIR, { recursive: true, force: true });
    fs.mkdirSync(HARNESS_DIR, { recursive: true });
    fs.writeFileSync(path.join(HARNESS_DIR, 'Harness.csproj'), CSPROJ, 'utf8');
    fs.writeFileSync(path.join(HARNESS_DIR, 'Program.cs'),
        PROGRAM.replace(/\{NAMESPACE\}/g, APP), 'utf8');

    // 3) build the app first (see headless.test.js for why the order matters), then the driver
    const appProj = path.join(OUT_DIR, APP, APP + '.csproj');
    const pre = t.run(`dotnet build "${appProj}" -c Debug`, { cwd: DIR });
    t.ok(pre.ok, 'runtime', 'the generated project builds (Timer.cs compiles)',
        pre.ok ? '' : String(pre.output).slice(-600));

    t.note('dotnet run TimerHarness (first build restores packages — can take a minute)…');
    const r = t.run('dotnet run --project "Harness.csproj" -c Debug', { cwd: HARNESS_DIR });
    const out = r.output || '';
    t.ok(r.ok, 'runtime', 'driver exits 0', r.ok ? '' : out.slice(-800));
    t.ok(out.includes('RESULT PASS'), 'runtime', 'final RESULT PASS',
        'RESULT line: ' + (out.match(/RESULT \w+/) || ['missing'])[0]);
    t.equal((out.match(/^FAIL /gm) || []).length, 0, 'runtime', 'no FAIL lines',
        out.split('\n').filter((l) => l.startsWith('FAIL ')).join(' | ').slice(0, 300));
    for (const name of ['timer-found', 'component-invisible', 'component-takes-no-space', 'started-from-xaml',
        'interval-from-xaml', 'xaml-bound-handler-ran', 'ticks', 'ticks-on-a-worker-thread', 'not-the-ui-thread',
        'stop-stops-it', 'start-starts-it-again', 'close-stops-it']) {
        t.ok(out.includes('PASS ' + name), 'runtime', name,
            out.includes('FAIL ' + name) ? 'reported FAIL' : '');
    }
    t.note(`artefacts in ${DIR}`);
};
