/**
 * controlEvents.ts — the event catalog behind the designer's event picker, the generated handler
 * stubs and the "Events per Control.md" reference in the project root.
 *
 * PROVENANCE: every event name and every EventArgs type below was generated by reflecting over the
 * REAL Avalonia 12.1.1 assemblies (Avalonia.Controls / Avalonia.Base / DataGrid) — the same version
 * the generated projects and the preview host target. That accuracy matters most for **VB.NET**: it
 * is strict about handler signatures (AVLN:0004) where C# is loose, so a wrong EventArgs type turns
 * "wire this event" into a build error.
 *
 * Three layers:
 *   - `EVENTS_BY_CONTROL` — the CURATED list the picker offers per control type, default event first;
 *   - `GENERIC_EVENTS` — fallback for a control without a curated entry;
 *   - `EVENT_ARGS` (+ per-control overrides) — the EventArgs type of an event, used for the stub.
 *
 * Regenerate after an Avalonia upgrade (see the footer of "Events per Control.md").
 */

/** The event wired when the picker is off, and the row preselected when it opens. */
export const DEFAULT_EVENT: Record<string, string> = {
    Button: 'Click',
    CheckBox: 'IsCheckedChanged',
    RadioButton: 'IsCheckedChanged',
    ComboBox: 'SelectionChanged',
    ListBox: 'SelectionChanged',
    TabControl: 'SelectionChanged',
    DataGrid: 'SelectionChanged',
    TextBox: 'TextChanged',
    HyperlinkButton: 'Click',
    CommandBarButton: 'Click',
    CommandBarToggleButton: 'IsCheckedChanged'
};

/**
 * Control types that ASK which event to wire when they are placed (the `askEventOnPlace` setting).
 * Everything else is placed silently — a panel/shape/label has no meaningful default event, but its
 * events are still offered when you right-click it and pick **Add event**.
 */
export const EVENT_PICKER_TAGS: readonly string[] = [
    'Button', 'CheckBox', 'RadioButton', 'ComboBox', 'ListBox', 'TabControl', 'DataGrid', 'TextBox',
    'HyperlinkButton', 'CommandBarButton', 'CommandBarToggleButton', 'Menu', 'MenuItem', 'Slider',
    'ProgressBar', 'ToggleSwitch', 'ToggleButton', 'RepeatButton', 'DropDownButton', 'SplitButton',
    'ToggleSplitButton', 'NumericUpDown', 'AutoCompleteBox', 'DatePicker', 'CalendarDatePicker',
    'TimePicker', 'TreeView'
];

/** The events worth wiring on a form, per control type — the picker's list, default event first. */
export const EVENTS_BY_CONTROL: Record<string, string[]> = {
    Button: ['Click', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'ContextRequested', 'ContextCanceled', 'Loaded', 'Unloaded'],
    RepeatButton: ['Click', 'Tapped', 'DoubleTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    DropDownButton: ['Click', 'Tapped', 'DoubleTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    SplitButton: ['Click', 'Tapped', 'DoubleTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    ToggleSplitButton: ['Click', 'IsCheckedChanged', 'Tapped', 'DoubleTapped', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    HyperlinkButton: ['Click', 'Tapped', 'DoubleTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    CommandBarButton: ['Click', 'Tapped', 'DoubleTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    CommandBarToggleButton: ['IsCheckedChanged', 'Click', 'Tapped', 'DoubleTapped', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    CheckBox: ['IsCheckedChanged', 'Click', 'Tapped', 'DoubleTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    RadioButton: ['IsCheckedChanged', 'Click', 'Tapped', 'DoubleTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    ToggleButton: ['IsCheckedChanged', 'Click', 'Tapped', 'DoubleTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    ToggleSwitch: ['IsCheckedChanged', 'Click', 'Tapped', 'DoubleTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    ComboBox: ['SelectionChanged', 'DropDownOpened', 'DropDownClosed', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    ComboBoxItem: ['DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    ListBox: ['SelectionChanged', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    ListBoxItem: ['DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    ItemsControl: ['DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    TabControl: ['SelectionChanged', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    TabItem: ['DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    TreeView: ['SelectionChanged', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    TreeViewItem: ['Expanded', 'Collapsed', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    Expander: ['Expanding', 'Expanded', 'Collapsing', 'Collapsed', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    DataGrid: ['SelectionChanged', 'BeginningEdit', 'CellEditEnding', 'CellEditEnded', 'PreparingCellForEdit', 'RowEditEnding', 'RowEditEnded', 'CurrentCellChanged', 'Sorting', 'AutoGeneratingColumn', 'LoadingRow', 'UnloadingRow', 'ColumnReordered', 'ColumnDisplayIndexChanged', 'DoubleTapped', 'Tapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'Loaded', 'Unloaded'],
    TextBox: ['TextChanged', 'TextChanging', 'KeyDown', 'KeyUp', 'TextInput', 'CopyingToClipboard', 'CuttingToClipboard', 'PastingFromClipboard', 'GotFocus', 'LostFocus', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'Loaded', 'Unloaded'],
    MaskedTextBox: ['TextChanged', 'TextChanging', 'KeyDown', 'KeyUp', 'TextInput', 'GotFocus', 'LostFocus', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'Loaded', 'Unloaded'],
    AutoCompleteBox: ['TextChanged', 'SelectionChanged', 'DropDownOpened', 'DropDownClosed', 'Populating', 'Populated', 'KeyDown', 'KeyUp', 'GotFocus', 'LostFocus', 'Loaded', 'Unloaded', 'Tapped'],
    NumericUpDown: ['ValueChanged', 'Spinned', 'KeyDown', 'KeyUp', 'GotFocus', 'LostFocus', 'Loaded', 'Unloaded', 'Tapped'],
    Slider: ['ValueChanged', 'PointerPressed', 'PointerReleased', 'KeyDown', 'KeyUp', 'GotFocus', 'LostFocus', 'Loaded', 'Unloaded', 'Tapped'],
    ProgressBar: ['ValueChanged', 'Loaded', 'Unloaded'],
    DatePicker: ['SelectedDateChanged', 'KeyDown', 'KeyUp', 'GotFocus', 'LostFocus', 'Loaded', 'Unloaded', 'Tapped'],
    CalendarDatePicker: ['SelectedDateChanged', 'CalendarOpened', 'CalendarClosed', 'DateValidationError', 'KeyDown', 'KeyUp', 'GotFocus', 'LostFocus', 'Loaded', 'Unloaded', 'Tapped'],
    TimePicker: ['SelectedTimeChanged', 'KeyDown', 'KeyUp', 'GotFocus', 'LostFocus', 'Loaded', 'Unloaded', 'Tapped'],
    Menu: ['Opened', 'Closed', 'SelectionChanged', 'Loaded', 'Unloaded'],
    MenuItem: ['Click', 'SubmenuOpened', 'PointerEntered', 'PointerExited', 'Loaded', 'Unloaded'],
    ContextMenu: ['Opened', 'Closed', 'Loaded', 'Unloaded'],
    CommandBar: ['Opened', 'Closing', 'Closed', 'Tapped', 'DoubleTapped', 'Loaded', 'Unloaded'],
    Window: ['Opened', 'Closing', 'Closed', 'Activated', 'Deactivated', 'Resized', 'PositionChanged', 'SizeChanged', 'KeyDown', 'KeyUp', 'GotFocus', 'LostFocus', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'Loaded', 'Unloaded'],
    WindowBase: ['Opened', 'Closed', 'Activated', 'Deactivated', 'Resized', 'PositionChanged', 'Loaded', 'Unloaded'],
    UserControl: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    ContentControl: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    Border: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp', 'ContextRequested'],
    Panel: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    Grid: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    StackPanel: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    DockPanel: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    WrapPanel: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    UniformGrid: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    Canvas: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    RelativePanel: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    ScrollViewer: ['ScrollChanged', 'Loaded', 'Unloaded', 'SizeChanged', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    Viewbox: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus'],
    GroupBox: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    Image: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    TextBlock: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    SelectableTextBlock: ['Loaded', 'Unloaded', 'Tapped', 'DoubleTapped', 'GotFocus', 'LostFocus'],
    Label: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'PointerEntered', 'PointerExited', 'GotFocus', 'LostFocus', 'KeyDown', 'KeyUp'],
    PathIcon: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus'],
    Rectangle: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'ContextRequested'],
    Ellipse: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'ContextRequested'],
    Line: ['Loaded', 'Unloaded', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus'],
    Arc: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'ContextRequested'],
    Path: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'ContextRequested'],
    Polygon: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'ContextRequested'],
    Polyline: ['Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree', 'DoubleTapped', 'Tapped', 'RightTapped', 'PointerPressed', 'PointerReleased', 'GotFocus', 'LostFocus', 'ContextRequested'],
    Separator: ['Loaded', 'Unloaded'],
};

/**
 * Fallback list for a control type without a curated entry: lifecycle, pointer, keyboard and focus —
 * the events every `Control` exposes.
 */
export const GENERIC_EVENTS: readonly string[] = [
    'Loaded', 'Unloaded', 'SizeChanged', 'AttachedToVisualTree', 'DetachedFromVisualTree',
    'Tapped', 'DoubleTapped', 'RightTapped', 'PointerPressed', 'PointerReleased',
    'PointerEntered', 'PointerExited', 'PointerWheelChanged', 'GotFocus', 'LostFocus', 'KeyDown',
    'KeyUp'
];

/**
 * The EventArgs type of an event, `sender`-delegate style: the handler is always
 * `(object sender, <type> e)` / `(sender As Object, e As <type>)`. Fully qualified, so a
 * generated stub needs no extra `using`/`Imports`.
 */
export const EVENT_ARGS: Record<string, string> = {
    'Activated': 'System.EventArgs',
    'ActualThemeVariantChanged': 'System.EventArgs',
    'AttachedToLogicalTree': 'Avalonia.LogicalTree.LogicalTreeAttachmentEventArgs',
    'AttachedToVisualTree': 'Avalonia.VisualTreeAttachmentEventArgs',
    'AutoGeneratingColumn': 'Avalonia.Controls.DataGridAutoGeneratingColumnEventArgs',
    'BackRequested': 'Avalonia.Interactivity.RoutedEventArgs',
    'BeginningEdit': 'Avalonia.Controls.DataGridBeginningEditEventArgs',
    'CalendarClosed': 'System.EventArgs',
    'CalendarOpened': 'System.EventArgs',
    'CellEditEnded': 'Avalonia.Controls.DataGridCellEditEndedEventArgs',
    'CellEditEnding': 'Avalonia.Controls.DataGridCellEditEndingEventArgs',
    'CellPointerPressed': 'Avalonia.Controls.DataGridCellPointerPressedEventArgs',
    'Click': 'Avalonia.Interactivity.RoutedEventArgs',
    'Closed': 'Avalonia.Interactivity.RoutedEventArgs',
    'Closing': 'Avalonia.Controls.WindowClosingEventArgs',
    'Collapsed': 'Avalonia.Interactivity.RoutedEventArgs',
    'Collapsing': 'Avalonia.Interactivity.CancelRoutedEventArgs',
    'ColumnDisplayIndexChanged': 'Avalonia.Controls.DataGridColumnEventArgs',
    'ColumnReordered': 'Avalonia.Controls.DataGridColumnEventArgs',
    'ColumnReordering': 'Avalonia.Controls.DataGridColumnReorderingEventArgs',
    'ContainerClearing': 'Avalonia.Controls.ContainerClearingEventArgs',
    'ContainerIndexChanged': 'Avalonia.Controls.ContainerIndexChangedEventArgs',
    'ContainerPrepared': 'Avalonia.Controls.ContainerPreparedEventArgs',
    'ContextCanceled': 'Avalonia.Interactivity.RoutedEventArgs',
    'ContextRequested': 'Avalonia.Input.ContextRequestedEventArgs',
    'CopyingRowClipboardContent': 'Avalonia.Controls.DataGridRowClipboardEventArgs',
    'CopyingToClipboard': 'Avalonia.Interactivity.RoutedEventArgs',
    'CurrentCellChanged': 'System.EventArgs',
    'CuttingToClipboard': 'Avalonia.Interactivity.RoutedEventArgs',
    'DataContextChanged': 'System.EventArgs',
    'DateValidationError': 'Avalonia.Controls.CalendarDatePickerDateValidationErrorEventArgs',
    'Deactivated': 'System.EventArgs',
    'DetachedFromLogicalTree': 'Avalonia.LogicalTree.LogicalTreeAttachmentEventArgs',
    'DetachedFromVisualTree': 'Avalonia.VisualTreeAttachmentEventArgs',
    'DisplayDateChanged': 'Avalonia.Controls.CalendarDateChangedEventArgs',
    'DisplayModeChanged': 'Avalonia.Controls.CalendarModeChangedEventArgs',
    'DoubleTapped': 'Avalonia.Input.TappedEventArgs',
    'DragCompleted': 'Avalonia.Input.VectorEventArgs',
    'DragDelta': 'Avalonia.Input.VectorEventArgs',
    'DragStarted': 'Avalonia.Input.VectorEventArgs',
    'DropDownClosed': 'System.EventArgs',
    'DropDownClosing': 'System.ComponentModel.CancelEventArgs',
    'DropDownOpened': 'System.EventArgs',
    'DropDownOpening': 'System.ComponentModel.CancelEventArgs',
    'EffectiveViewportChanged': 'Avalonia.Layout.EffectiveViewportChangedEventArgs',
    'Expanded': 'Avalonia.Interactivity.RoutedEventArgs',
    'Expanding': 'Avalonia.Interactivity.CancelRoutedEventArgs',
    'GettingFocus': 'Avalonia.Input.FocusChangingEventArgs',
    'GotFocus': 'Avalonia.Input.FocusChangedEventArgs',
    'HeaderPointerPressed': 'Avalonia.Input.PointerPressedEventArgs',
    'HeaderPointerReleased': 'Avalonia.Input.PointerReleasedEventArgs',
    'Holding': 'Avalonia.Input.HoldingRoutedEventArgs',
    'HorizontalScroll': 'Avalonia.Controls.Primitives.ScrollEventArgs',
    'HorizontalSnapPointsChanged': 'Avalonia.Interactivity.RoutedEventArgs',
    'Initialized': 'System.EventArgs',
    'IsCheckedChanged': 'Avalonia.Interactivity.RoutedEventArgs',
    'KeyDown': 'Avalonia.Input.KeyEventArgs',
    'KeyUp': 'Avalonia.Input.KeyEventArgs',
    'LayoutUpdated': 'System.EventArgs',
    'LeftClick': 'Avalonia.Input.KeyModifiers',
    'Loaded': 'Avalonia.Interactivity.RoutedEventArgs',
    'LoadingRow': 'Avalonia.Controls.DataGridRowEventArgs',
    'LoadingRowDetails': 'Avalonia.Controls.DataGridRowDetailsEventArgs',
    'LoadingRowGroup': 'Avalonia.Controls.DataGridRowGroupHeaderEventArgs',
    'LosingFocus': 'Avalonia.Input.FocusChangingEventArgs',
    'LostFocus': 'Avalonia.Input.FocusChangedEventArgs',
    'Opened': 'Avalonia.Interactivity.RoutedEventArgs',
    'Opening': 'Avalonia.Interactivity.RoutedEventArgs',
    'PaneClosed': 'Avalonia.Interactivity.RoutedEventArgs',
    'PaneClosing': 'Avalonia.Interactivity.CancelRoutedEventArgs',
    'PaneOpened': 'Avalonia.Interactivity.RoutedEventArgs',
    'PaneOpening': 'Avalonia.Interactivity.CancelRoutedEventArgs',
    'PastingFromClipboard': 'Avalonia.Interactivity.RoutedEventArgs',
    'Pinch': 'Avalonia.Input.PinchEventArgs',
    'PinchEnded': 'Avalonia.Input.PinchEndedEventArgs',
    'PointerCaptureLost': 'Avalonia.Input.PointerCaptureLostEventArgs',
    'PointerEntered': 'Avalonia.Input.PointerEventArgs',
    'PointerEnteredItem': 'Avalonia.Interactivity.RoutedEventArgs',
    'PointerExited': 'Avalonia.Input.PointerEventArgs',
    'PointerExitedItem': 'Avalonia.Interactivity.RoutedEventArgs',
    'PointerMoved': 'Avalonia.Input.PointerEventArgs',
    'PointerPressed': 'Avalonia.Input.PointerPressedEventArgs',
    'PointerReleased': 'Avalonia.Input.PointerReleasedEventArgs',
    'PointerTouchPadGestureMagnify': 'Avalonia.Input.PointerDeltaEventArgs',
    'PointerTouchPadGestureRotate': 'Avalonia.Input.PointerDeltaEventArgs',
    'PointerTouchPadGestureSwipe': 'Avalonia.Input.PointerDeltaEventArgs',
    'PointerWheelChanged': 'Avalonia.Input.PointerWheelEventArgs',
    'Populated': 'Avalonia.Controls.PopulatedEventArgs',
    'Populating': 'Avalonia.Controls.PopulatingEventArgs',
    'PositionChanged': 'Avalonia.Controls.PixelPointEventArgs',
    'PreparingCellForEdit': 'Avalonia.Controls.DataGridPreparingCellForEditEventArgs',
    'PreparingContainer': 'Avalonia.Controls.ContainerPreparedEventArgs',
    'PropertyChanged': 'Avalonia.AvaloniaPropertyChangedEventArgs',
    'PullGesture': 'Avalonia.Input.PullGestureEventArgs',
    'PullGestureEnded': 'Avalonia.Input.PullGestureEndedEventArgs',
    'RefreshRequested': 'Avalonia.Controls.RefreshRequestedEventArgs',
    'Resized': 'Avalonia.Controls.WindowResizedEventArgs',
    'ResourcesChanged': 'Avalonia.Controls.ResourcesChangedEventArgs',
    'RightTapped': 'Avalonia.Input.TappedEventArgs',
    'RowDetailsVisibilityChanged': 'Avalonia.Controls.DataGridRowDetailsEventArgs',
    'RowEditEnded': 'Avalonia.Controls.DataGridRowEditEndedEventArgs',
    'RowEditEnding': 'Avalonia.Controls.DataGridRowEditEndingEventArgs',
    'ScalingChanged': 'System.EventArgs',
    'Scroll': 'Avalonia.Controls.Primitives.ScrollEventArgs',
    'ScrollChanged': 'Avalonia.Controls.ScrollChangedEventArgs',
    'ScrollGesture': 'Avalonia.Input.ScrollGestureEventArgs',
    'ScrollGestureEnded': 'Avalonia.Input.ScrollGestureEndedEventArgs',
    'ScrollGestureInertiaStarting': 'Avalonia.Input.ScrollGestureInertiaStartingEventArgs',
    'SelectedDateChanged': 'Avalonia.Controls.SelectionChangedEventArgs',
    'SelectedDatesChanged': 'Avalonia.Controls.SelectionChangedEventArgs',
    'SelectedTimeChanged': 'Avalonia.Controls.TimePickerSelectedValueChangedEventArgs',
    'SelectionChanged': 'Avalonia.Controls.SelectionChangedEventArgs',
    'SizeChanged': 'Avalonia.Controls.SizeChangedEventArgs',
    'Sorting': 'Avalonia.Controls.DataGridColumnEventArgs',
    'Spin': 'Avalonia.Controls.SpinEventArgs',
    'Spinned': 'Avalonia.Controls.SpinEventArgs',
    'SubmenuOpened': 'Avalonia.Interactivity.RoutedEventArgs',
    'SwipeGesture': 'Avalonia.Input.SwipeGestureEventArgs',
    'SwipeGestureEnded': 'Avalonia.Input.SwipeGestureEndedEventArgs',
    'Tapped': 'Avalonia.Input.TappedEventArgs',
    'TemplateApplied': 'Avalonia.Controls.Primitives.TemplateAppliedEventArgs',
    'TextChanged': 'Avalonia.Controls.TextChangedEventArgs',
    'TextChanging': 'Avalonia.Controls.TextChangingEventArgs',
    'TextInput': 'Avalonia.Input.TextInputEventArgs',
    'TextInputMethodClientRequested': 'Avalonia.Input.TextInput.TextInputMethodClientRequestedEventArgs',
    'TransitionCompleted': 'Avalonia.Controls.TransitionCompletedEventArgs',
    'Unloaded': 'Avalonia.Interactivity.RoutedEventArgs',
    'UnloadingRow': 'Avalonia.Controls.DataGridRowEventArgs',
    'UnloadingRowDetails': 'Avalonia.Controls.DataGridRowDetailsEventArgs',
    'UnloadingRowGroup': 'Avalonia.Controls.DataGridRowGroupHeaderEventArgs',
    'ValueChanged': 'Avalonia.Controls.Primitives.RangeBaseValueChangedEventArgs',
    'VerticalScroll': 'Avalonia.Controls.Primitives.ScrollEventArgs',
    'VerticalSnapPointsChanged': 'Avalonia.Interactivity.RoutedEventArgs',
};

/** Where one event name maps to different EventArgs on different controls, the odd ones out. */
export const EVENT_ARGS_BY_CONTROL: Record<string, Record<string, string>> = {
    Window: { 'Opened': 'System.EventArgs', 'Closed': 'System.EventArgs' },
    WindowBase: { 'Opened': 'System.EventArgs', 'Closed': 'System.EventArgs' },
    NumericUpDown: { 'ValueChanged': 'Avalonia.Controls.NumericUpDownValueChangedEventArgs' },
    DatePicker: { 'SelectedDateChanged': 'Avalonia.Controls.DatePickerSelectedValueChangedEventArgs' },
};

/** The events the picker offers for a control type (curated list, else the generic one). */
export function eventsFor(tag: string): string[] {
    const curated = EVENTS_BY_CONTROL[tag];
    return curated && curated.length > 0 ? curated.slice() : GENERIC_EVENTS.slice();
}

/** The EventArgs type to write into a handler stub for `event` on `tag`. */
export function eventArgsFor(event: string, tag?: string): string {
    const override = tag ? EVENT_ARGS_BY_CONTROL[tag]?.[event] : undefined;
    return override ?? EVENT_ARGS[event] ?? 'Avalonia.Interactivity.RoutedEventArgs';
}

/** Does this control type get a picker when it is placed? */
export function asksForEventOnPlace(tag: string): boolean {
    return EVENT_PICKER_TAGS.includes(tag);
}

/** The event preselected in the picker (and wired silently when asking is off). */
export function defaultEventFor(tag: string): string {
    return DEFAULT_EVENT[tag] ?? 'DoubleTapped';
}

/** True for a control type with a specific default event (i.e. an interactive control). */
export function hasDefaultEvent(tag: string): boolean {
    return tag in DEFAULT_EVENT;
}

/** True when `name` is a known event of `tag` (used to recognise wired attributes). */
export function isKnownEvent(tag: string, name: string): boolean {
    return eventsFor(tag).includes(name) || name in EVENT_ARGS;
}

/** Event names Avalonia controls commonly wire that belong to NO catalog list, because they are
 *  specific to controls the picker lists separately (ToggleButton's Checked/Unchecked/Indeterminate,
 *  ItemsControl's ItemsSourceChanged, SelectingItemsControl's SelectionChanging, …).
 *
 *  They exist for RECOGNITION only: the code-behind checker must treat `Checked="Handler"` in a form
 *  as an event. They are deliberately NOT added to GENERIC_EVENTS — that list feeds the picker, and
 *  offering `Checked` on a plain Button would generate a handler for an event the control does not
 *  have, i.e. an XAML compile error. */
const COMMONLY_WIRED_EVENTS: readonly string[] = [
    'Click', 'DoubleTapped', 'Tapped', 'Loaded', 'Unloaded', 'Initialized', 'AttachedToVisualTree',
    'DetachedFromVisualTree', 'SelectionChanged', 'SelectionChanging', 'IsCheckedChanged',
    'TextChanged', 'TextChanging', 'KeyDown', 'KeyUp', 'GotFocus', 'LostFocus', 'PointerPressed',
    'PointerReleased', 'PointerMoved', 'PointerEntered', 'PointerExited', 'PointerWheelChanged',
    'Checked', 'Unchecked', 'Indeterminate', 'ValueChanged', 'Opened', 'Closed', 'Opening',
    'Closing', 'Tick', 'DataContextChanged', 'SizeChanged', 'LayoutUpdated', 'ScrollChanged',
    'DropDownOpened', 'DropDownClosed', 'ItemsSourceChanged', 'EffectiveViewportChanged',
    'PropertyChanged', 'ActualThemeVariantChanged', 'Holding', 'ContextRequested'
];

/** Every event name the catalog knows about: the EventArgs table + the generic list + every
 *  per-control curated list, plus the recognised-only names above. Derived rather than hand-written,
 *  because a second copy is exactly what drifts — the code-behind checker used to keep its own list
 *  and had silently stopped recognising 83 events the picker still offered (RightTapped on 45
 *  control types, every DataGrid edit event, Expander.*, DatePicker.SelectedDateChanged, …). */
export const KNOWN_EVENT_NAMES: ReadonlySet<string> = new Set<string>([
    ...Object.keys(EVENT_ARGS),
    ...GENERIC_EVENTS,
    ...Object.values(EVENTS_BY_CONTROL).flat(),
    ...COMMONLY_WIRED_EVENTS
]);

/** True when the catalog knows `name` as an event on SOME control (see KNOWN_EVENT_NAMES). */
export function isKnownEventName(name: string): boolean {
    return KNOWN_EVENT_NAMES.has(name);
}

/** The tag-aware EventArgs the code WRITER would emit — or `undefined` when the catalog does not
 *  actually know this event. The `undefined` matters: the checker must never guess a signature, or
 *  it would flag valid hand-written code. So `undefined` means "do not signature-check this one". */
export function knownEventArgsFor(event: string, tag?: string): string | undefined {
    const override = tag ? EVENT_ARGS_BY_CONTROL[tag]?.[event] : undefined;
    return override ?? EVENT_ARGS[event];
}
