import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { DOMParser } from '@xmldom/xmldom';
import { localName } from './xamlModel';
import { bindControlToDataSet, unbindControlFromDataSet, unbindImageFromGrid, hasDataSetBinding, DataSetBindingRef } from './codeBehind';
import {
    DataSetSpec, DataTableSpec, DataColumnSpec, ColumnType, parseDataSet, parseDataSetChecked, serializeDataSet, defaultDataSetSpec,
    isValidIdentifier, findTable, newTableSpec, newColumnSpec, COLUMN_TYPES, isSqliteTable, sanitizeName, sqliteTableName
} from './dataSetModel';
import { generateCs, generateVb, generateXsd, consolidateRuntimeHelpers } from './dataSetGenerator';
import { findProject, ProjectInfo } from './projectParser';
import { PreviewerHostManager } from './hostClient';

/** Control types that can display a DataSet table (they take an ItemsSource).
 *  TreeView is here for hierarchy tables: it needs `role` columns to build the nodes (see
 *  `canBindToTree`), which is why binding one is checked at bind time rather than by omission. */
const BINDABLE_TAGS = new Set(['DataGrid', 'ListBox', 'ComboBox', 'ItemsControl', 'TreeView']);

/** Reads a file, returning '' when it cannot be read. */
function readText(file: string): string {
    try { return fs.readFileSync(file, 'utf8'); } catch { return ''; }
}

/**
 * True for a class file this extension generated (the header marks it as ours). Only such files are ever
 * rewritten when the shared runtime helpers have to be de-duplicated — never the user's own code.
 */
function isGeneratedDataSetFile(file: string): boolean {
    return /Generated by the Avalonia Designer/.test(readText(file));
}

/** Recursively lists files under `dir` (skipping build/ignore folders). */
function walkProject(dir: string, out: string[]): void {
    let entries: string[] = [];
    try { entries = fs.readdirSync(dir); } catch { return; }
    for (const e of entries) {
        if (e === 'bin' || e === 'obj' || e === 'node_modules' || e === '.git' || e === '.vscode' || e.startsWith('.')) continue;
        const p = path.join(dir, e);
        let st;
        try { st = fs.statSync(p); } catch { continue; }
        if (st.isDirectory()) walkProject(p, out);
        else if (/\.axaml$/i.test(e)) out.push(p);
    }
}

/** The SQLite packages a generated project needs when a .adset table stores data in SQLite.
 *  Kept in sync with the host's PreviewerHost.csproj. The SQLitePCLRaw bundle is referenced
 *  directly so NuGet uses the patched native library (NU1903) regardless of the transitive pin. */
const SQLITE_PACKAGES = [
    '<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.1" />',
    '<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.13" />'
];

/** Adds the SQLite package references to the project file (idempotent), if a table uses SQLite.
 *  (Existing .db files are used in place — the app edits the absolute path — so no data files are
 *  copied to the output folder.) Exported so the form designer's Items Source picker can apply the
 *  same package injection the DataSet designer does when it binds a table. */
export function ensureSqlitePackages(proj: ProjectInfo | undefined, spec: DataSetSpec): void {
    if (!proj || !spec.tables.some((t) => isSqliteTable(t) || !!t.boundTo)) return;
    const file = proj.projectUri.fsPath;
    let text: string;
    try { text = fs.readFileSync(file, 'utf8'); } catch { return; }
    const items: string[] = [];
    for (const r of SQLITE_PACKAGES) {
        const name = r.split(' ')[1].replace('Include=', '').replace(/["/]/g, '');
        if (!text.includes(name)) items.push('    ' + r);
    }
    if (items.length === 0) return;
    const insert = items.join('\n');
    const ig = text.lastIndexOf('</ItemGroup>');
    if (ig >= 0) text = text.slice(0, ig) + insert + '\n' + text.slice(ig);
    else {
        const pj = text.lastIndexOf('</Project>');
        if (pj < 0) return;
        text = text.slice(0, pj) + '  <ItemGroup>\n' + insert + '\n  </ItemGroup>\n' + text.slice(pj);
    }
    fs.writeFileSync(file, text, 'utf8');
}

interface ScannedControl { name: string; type: string; axamlPath: string; }

/** Maps a SQLite column-affinity to the closest designer column type (used by Import). */
function sqliteAffinityToType(affinity: string): ColumnType {
    const a = (affinity || '').toUpperCase();
    if (a.startsWith('INT')) return 'Int32';
    if (a === 'REAL' || a === 'FLOAT' || a === 'DOUBLE') return 'Double';
    if (a.startsWith('NUM') || a === 'DECIMAL' || a === 'MONEY') return 'Decimal';
    if (a === 'BOOLEAN' || a === 'BOOL') return 'Boolean';
    if (a.startsWith('DATE') || a === 'TIME' || a === 'DATETIME') return 'DateTime';
    if (a === 'BLOB') return 'Byte[]';
    return 'String'; // TEXT and anything unknown
}

/** A unique table name for a table being imported into the spec. */
function uniqueTableName(spec: DataSetSpec, base: string): string {
    const clean = sanitizeName(base) || 'Table';
    const used = new Set(spec.tables.map((t) => t.name.toLowerCase()));
    let name = clean;
    let i = 1;
    while (used.has(name.toLowerCase())) { i += 1; name = `${clean}${i}`; }
    return name;
}

/** Default SQLite file for a DataSet (a shared per-dataset .db next to the app). Exported so the
 *  form designer's Items Source picker defaults a newly-bound no-storage table to the same file the
 *  DataSet designer would use. */
export function defaultDbFile(spec: DataSetSpec): string {
    return `${spec.name}.db`;
}

/** True when `<name>.db` already exists under `folder` (project root). A new or renamed DataSet with
 *  that name would silently read/write an EXISTING database, so the caller warns before proceeding. */
function defaultDbExists(folder: string, name: string): boolean {
    return fs.existsSync(path.join(folder, `${name}.db`));
}

/** Resolves a (possibly relative) sqlite.file to an existing path for design-time preview.
 *  The generated app resolves relative files next to the EXE (bin/...), so try the project
 *  folder first, then the bin folders. Falls back to the project-folder path. */
function resolveDbPath(projectDir: string | undefined, file: string): string {
    if (path.isAbsolute(file)) return file;
    const candidates: string[] = [];
    if (projectDir) {
        candidates.push(path.join(projectDir, file));
        for (const cfg of ['Debug', 'Release']) {
            for (const tfm of ['net10.0', 'net8.0']) {
                candidates.push(path.join(projectDir, 'bin', cfg, tfm, file));
            }
        }
    }
    candidates.push(file);
    for (const c of candidates) { if (fs.existsSync(c)) return c; }
    return candidates[0] ?? file;
}


/**
 * Avalonia's DataGrid defaults AutoGenerateColumns to FALSE, so a bound DataGrid would show no
 * columns/headers/rows. When binding to a DataGrid, make sure the XAML element carries
 * AutoGenerateColumns="True" (idempotent; respects an explicit False). Edits the .axaml in place.
 */
import { TREE_COLUMN_ROLES, canBindToTree } from './dataSetModel';

/**
 * Binds a TreeView to a table (2026-09-18): the one thing the FORM needs for a tree that a grid does not is
 * an **ItemTemplate** — a TreeView shows its `ItemsSource`, and without a `TreeDataTemplate` every node
 * renders as its type name.
 *
 * It also clears inline `<TreeViewItem>` nodes, because Avalonia throws "Items collection must be empty
 * before using ItemsSource" — the same rule the ComboBox/ListBox items editors enforce. Those nodes were the
 * user's static tree, so the caller reports it on the status line rather than removing them silently.
 *
 * Returns what it did, for that message.
 */
export function ensureTreeItemTemplate(axamlPath: string, controlName: string): 'template' | 'cleared' | 'both' | 'none' {
    let text = '';
    try { text = fs.readFileSync(axamlPath, 'utf8'); } catch { return 'none'; }
    const esc = controlName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const open = new RegExp(`<TreeView\\b(?=[^>]*x:Name\\s*=\\s*["']${esc}["'])([^>]*?)(/?)(>)`).exec(text);
    if (!open) return 'none';
    const attrs = open[1];
    const selfClosed = open[2] === '/';
    const closeAt = selfClosed ? -1 : text.indexOf('</TreeView>', open.index + open[0].length);
    let inner = selfClosed ? '' : (closeAt > 0 ? text.slice(open.index + open[0].length, closeAt) : '');
    const template = /<TreeView\.ItemTemplate\b/.test(inner)
        ? ''
        : '\n  <TreeView.ItemTemplate>\n    <TreeDataTemplate ItemsSource="{Binding Children}">\n'
        + '      <TextBlock Text="{Binding Header}"/>\n    </TreeDataTemplate>\n  </TreeView.ItemTemplate>';
    let cleared = false;
    // Nested nodes make this a loop: the pattern is non-greedy, so one pass removes a leaf, the next its parent.
    while (/<TreeViewItem\b/.test(inner)) {
        const before = inner;
        inner = inner.replace(/[ \t]*<TreeViewItem\b[\s\S]*?<\/TreeViewItem>[ \t]*\r?\n?/g, '')
            .replace(/[ \t]*<TreeViewItem\b[^>]*\/>[ \t]*\r?\n?/g, '');
        cleared = true;
        if (inner === before) {
            inner = inner.replace(/<\/?TreeViewItem\b[^>]*>/g, '');
            break;
        }
    }
    if (!template && !cleared) return 'none';
    const updated = selfClosed
        ? text.slice(0, open.index) + `<TreeView${attrs}>${template}${inner}\n</TreeView>` + text.slice(open.index + open[0].length)
        : text.slice(0, open.index + open[0].length) + template + inner + text.slice(closeAt);
    fs.writeFileSync(axamlPath, updated, 'utf8');
    return template && cleared ? 'both' : (template ? 'template' : 'cleared');
}

export function ensureDataGridAutoGenerateColumns(axamlPath: string, controlName: string): boolean {
    let text = '';
    try { text = fs.readFileSync(axamlPath, 'utf8'); } catch { return false; }
    const esc = controlName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp(`<((?:dg:)?DataGrid)\\b(?=[^>]*x:Name\\s*=\\s*["']${esc}["'])(?![^>]*\\bAutoGenerateColumns\\b)([^>]*?)(/?)>`, 'i');
    const updated = text.replace(re, (_m, tag: string, attrs: string, selfClose: string) =>
        `<${tag} AutoGenerateColumns="True"${attrs}${selfClose ? '/' : ''}>`);
    if (updated === text) return false;
    fs.writeFileSync(axamlPath, updated, 'utf8');
    return true;
}

/** Returns the .axaml file (if any) that contains a control with the given x:Name. */
function findFormWithControl(projectFolder: string, controlName: string): string | undefined {
    const files: string[] = [];
    walkProject(projectFolder, files);
    for (const f of files) {
        if (!/\.axaml$/i.test(f)) continue;
        try {
            const text = fs.readFileSync(f, 'utf8');
            const re = new RegExp(`x:Name\\s*=\\s*\"${controlName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\"`);
            if (re.test(text)) return f;
        } catch { /* keep scanning */ }
    }
    return undefined;
}

/** Finds every named bindable control in the project's .axaml files. */
function scanBindableControls(projectFolder: string): ScannedControl[] {
    const files: string[] = [];
    walkProject(projectFolder, files);
    const out: ScannedControl[] = [];
    const parser = new DOMParser();
    for (const f of files) {
        let text = '';
        try { text = fs.readFileSync(f, 'utf8'); } catch { continue; }
        let doc: any;
        try { doc = parser.parseFromString(text, 'text/xml'); } catch { continue; }
        if (!doc || !doc.documentElement) continue;
        const walk = (el: Element): void => {
            const ln = localName(el.tagName);
            if (ln.includes('.')) { for (const c of Array.from(el.childNodes)) if (c.nodeType === 1) walk(c as Element); return; }
            if (BINDABLE_TAGS.has(ln)) {
                const n = el.getAttribute('x:Name') || el.getAttribute('Name');
                if (n) out.push({ name: n, type: ln, axamlPath: f });
            }
            for (const c of Array.from(el.childNodes)) if (c.nodeType === 1) walk(c as Element);
        };
        walk(doc.documentElement);
    }
    return out;
}

/**
 * Collects every control name already bound to a dataset — this spec plus all other
 * .adset files in the project — so the dropdown can mark them with '*'.
 */
function scanBoundMarkers(projectFolder: string, current: DataSetSpec): Set<string> {
    const markers = new Set<string>();
    for (const t of current.tables) if (t.boundTo) markers.add(t.boundTo);
    const files: string[] = [];
    walkProject(projectFolder, files);
    for (const f of files) {
        if (!/\.adset$/i.test(f)) continue;
        let text = '';
        try { text = fs.readFileSync(f, 'utf8'); } catch { continue; }
        try {
            for (const t of parseDataSet(text).tables) if (t.boundTo) markers.add(t.boundTo);
        } catch { /* ignore */ }
    }
    return markers;
}

/**
 * In-memory .adset document. The DataSetSpec (JSON) is the source of truth; the
 * webview only renders it.
 */
export class DataSetDocument implements vscode.CustomDocument {
    spec: DataSetSpec;
    readonly uri: vscode.Uri;
    /** Set when the file on disk did NOT parse as a `.adset`. While it is set the document must never
     *  be written back: the in-memory spec is a recovery, so saving it would replace whatever the
     *  file really contains with an empty schema. */
    parseError?: string;
    private savedJson: string;

    private constructor(uri: vscode.Uri, spec: DataSetSpec) {
        this.uri = uri;
        this.spec = spec;
        this.savedJson = serializeDataSet(spec);
    }

    static async create(uri: vscode.Uri): Promise<DataSetDocument> {
        const data = await vscode.workspace.fs.readFile(uri);
        const { spec, error } = parseDataSetChecked(Buffer.from(data).toString('utf8'));
        const doc = new DataSetDocument(uri, spec);
        if (error) {
            // Tell the user immediately instead of silently showing an empty schema they might then
            // save over their own file.
            doc.parseError = error;
            void vscode.window.showErrorMessage(
                `${path.basename(uri.fsPath)} could not be read as a DataSet (${error}). It is shown ` +
                'with a recovered, empty schema and will NOT be saved over — fix or delete the file, ' +
                'then reopen it.');
        }
        return doc;
    }

    get dirty(): boolean { return serializeDataSet(this.spec) !== this.savedJson; }
    markSaved(): void { this.savedJson = serializeDataSet(this.spec); }
    dispose(): void { /* nothing to clean up */ }
}

/**
 * Live DataSet designer panels (keyed by document URI). The DataSet editor keeps its schema
 * in memory; when the FORM designer binds/unbinds a table through the Items Source picker it
 * writes the .adset straight to disk, so any DataSet panel already open for that file would
 * otherwise keep showing the stale (unbound) schema. Each open panel registers a reloader
 * closure here that re-reads the file, swaps the in-memory spec, resets the undo history and
 * repaints the panel.
 */
const liveReloaders = new Map<string, () => Promise<void>>();

/**
 * Per-open-DataSet "save if dirty" hooks (keyed by document URI). A custom editor's unsaved state is
 * invisible to `vscode.workspace.saveAll`, so the form designer's **Project Backup** button asks
 * here first — otherwise the backup would miss schema edits sitting in the DataSet designer.
 */
const dirtySavers = new Map<string, () => Promise<boolean>>();

/** Saves every open DataSet document that has unsaved changes; returns their file names (empty when
 *  nothing was dirty). A failed save is skipped, so one bad file can't abort a backup. */
export async function saveOpenDataSetDocuments(): Promise<string[]> {
    const saved: string[] = [];
    for (const [key, save] of [...dirtySavers]) {
        try {
            if (await save()) saved.push(vscode.Uri.parse(key).path.split('/').pop() || key);
        } catch { /* keep going — the caller reports what it saved */ }
    }
    return saved;
}

/**
 * If the .adset at `uri` is currently open in a DataSet designer panel, reloads it from disk
 * and repaints the panel (and resets its undo history, since an external change can't be
 * meaningfully undone). Returns true when a panel was refreshed.
 */
export async function reloadDataSetPanel(uri: vscode.Uri): Promise<boolean> {
    const reload = liveReloaders.get(uri.toString());
    if (!reload) return false;
    await reload();
    return true;
}

/**
 * Custom editor for `*.adset` files — a visual DataSet schema designer
 * (runtime-construction DataSets, not strongly-typed codegen).
 */
export class DataSetEditorProvider implements vscode.CustomEditorProvider<DataSetDocument> {
    static readonly viewType = 'avaloniaDesigner.dataSetDesigner';

    private readonly _onDidChangeCustomDocument = new vscode.EventEmitter<vscode.CustomDocumentEditEvent<DataSetDocument>>();
    readonly onDidChangeCustomDocument = this._onDidChangeCustomDocument.event;

    private readonly panels = new Map<string, vscode.WebviewPanel>();
    private readonly docs = new Map<string, DataSetDocument>();
    /** Undo/redo history: 5 levels deep = up to 6 serialized-spec snapshots (current + 5 prior). */
    private readonly history = new Map<string, { states: string[]; index: number }>();
    /** Previewer host — runs the design-time SQLite queries against the user's .db file. */
    private readonly host: PreviewerHostManager;

    constructor(private readonly context: vscode.ExtensionContext) {
        this.host = new PreviewerHostManager(context);
        context.subscriptions.push(this.host);
    }

    async openCustomDocument(uri: vscode.Uri): Promise<DataSetDocument> {
        const doc = await DataSetDocument.create(uri);
        this.docs.set(uri.toString(), doc);
        return doc;
    }

    async resolveCustomEditor(document: DataSetDocument, webviewPanel: vscode.WebviewPanel): Promise<void> {
        const key = document.uri.toString();
        this.panels.set(key, webviewPanel);

        webviewPanel.webview.options = {
            enableScripts: true,
            localResourceRoots: [this.context.extensionUri]
        };
        webviewPanel.webview.html = this.webviewHtml(webviewPanel.webview);

        // Register this panel's reloader so a binding change made from the form designer's
        // Items Source picker is reflected here live (see reloadDataSetPanel above).
        liveReloaders.set(key, async () => {
            try {
                const text = fs.readFileSync(document.uri.fsPath, 'utf8');
                document.spec = parseDataSet(text);
                document.markSaved();
                // An external edit can't be undone meaningfully — start a fresh history.
                this.history.set(key, { states: [serializeDataSet(document.spec)], index: 0 });
                await this.postState(document, webviewPanel);
            } catch { /* keep the current in-memory state on failure */ }
        });

        // Register this panel's "save if dirty" hook too, so Project Backup writes the schema the
        // designer still holds in memory (see saveOpenDataSetDocuments).
        dirtySavers.set(key, async () => {
            if (!document.dirty) return false;
            // A recovered schema must never be written over the file it failed to read.
            if (document.parseError) return false;
            await vscode.workspace.fs.writeFile(document.uri, Buffer.from(serializeDataSet(document.spec), 'utf8'));
            document.markSaved();
            return true;
        });

        webviewPanel.onDidDispose(() => {
            liveReloaders.delete(key);
            dirtySavers.delete(key);
            this.panels.delete(key);
            this.docs.delete(key);
            this.history.delete(key);
        });
        webviewPanel.webview.onDidReceiveMessage((msg) => void this.handleMessage(document, webviewPanel, msg));
    }

    // ---------------------------------------------------------------- messages
    private async handleMessage(doc: DataSetDocument, panel: vscode.WebviewPanel, msg: any): Promise<void> {
        const before = serializeDataSet(doc.spec);
        try {
            switch (msg.type) {
                case 'ready':
                    if (!this.history.has(doc.uri.toString())) {
                        this.history.set(doc.uri.toString(), { states: [serializeDataSet(doc.spec)], index: 0 });
                    }
                    await this.postState(doc, panel);
                    return;

                case 'undo':
                case 'redo':
                    await this.undoRedo(doc, panel, msg.type === 'redo');
                    return;

                case 'setName': {
                    // The DataSet name is fixed when the .adset is created. Renaming it here would
                    // leave the OLD generated class/.xsd (and any code-behind bindings under the old
                    // class name) behind while Generate writes a NEW file — duplicating the shared
                    // helper types (DatabaseAdapter/CustomersRow/dialogs → BC30179) and stranding
                    // references. Supported rename path: Remove DataSet, then create a new one.
                    await this.postStatus(panel, 'The DataSet name is fixed when created. To rename, use Remove DataSet… then create a new DataSet.');
                    await this.postState(doc, panel); // revert the name field
                    return;
                }

                case 'setTableName': {
                    const t = findTable(doc.spec, String(msg.oldName ?? ''));
                    const v = typeof msg.name === 'string' ? msg.name.trim() : '';
                    if (t && v && v !== t.name) {
                        if (!isValidIdentifier(v)) {
                            await this.postStatus(panel, 'The table name must be a single word (letters/numbers/underscore).');
                        } else if (findTable(doc.spec, v)) {
                            await this.postStatus(panel, `A table named "${v}" already exists.`);
                        } else {
                            t.name = v;
                            this.notifyEdit(doc, panel, before);
                        }
                    }
                    await this.postState(doc, panel);
                    return;
                }

                case 'setColumnProp': {
                    const t = findTable(doc.spec, String(msg.table ?? ''));
                    const c = t?.columns.find((x) => x.name === String(msg.column ?? ''));
                    if (t && c) {
                        const prop = String(msg.prop ?? '');
                        if (prop === 'name') {
                            const v = typeof msg.value === 'string' ? msg.value.trim() : '';
                            if (v && v !== c.name) {
                                if (!isValidIdentifier(v)) {
                                    await this.postStatus(panel, 'The column name must be a single word (letters/numbers/underscore).');
                                } else if (t.columns.some((x) => x.name === v)) {
                                    await this.postStatus(panel, `A column named "${v}" already exists in ${t.name}.`);
                                } else {
                                    c.name = v;
                                    this.notifyEdit(doc, panel, before);
                                }
                            }
                        } else if (prop === 'caption') {
                            c.caption = String(msg.value ?? '');
                            this.notifyEdit(doc, panel, before);
                        } else if (prop === 'type') {
                            const v = String(msg.value ?? '');
                            if ((COLUMN_TYPES as string[]).includes(v)) {
                                c.type = v as DataSetSpec['tables'][number]['columns'][number]['type'];
                                this.notifyEdit(doc, panel, before);
                            }
                        } else if (prop === 'allowNull') {
                            c.allowNull = msg.value !== false;
                            this.notifyEdit(doc, panel, before);
                        } else if (prop === 'role') {
                            // What this column MEANS when the table is bound to a TreeView ('' clears it). The
                            // list is the spec's own, so the editor and the generator cannot disagree about roles.
                            const v = String(msg.value ?? '');
                            c.role = (TREE_COLUMN_ROLES as string[]).includes(v)
                                ? (v as NonNullable<typeof c.role>)
                                : null;
                            this.notifyEdit(doc, panel, before);
                        } else if (prop === 'sampleValue') {
                            const v = String(msg.value ?? '');
                            c.sampleValue = v ? v : null;
                            this.notifyEdit(doc, panel, before);
                        } else if (prop === 'key') {
                            // Primary key flag — only one key column per table.
                            if (msg.value === true) {
                                if (t.keyColumn !== c.name) { t.keyColumn = c.name; this.notifyEdit(doc, panel, before); }
                            } else if (t.keyColumn === c.name) {
                                t.keyColumn = null;
                                this.notifyEdit(doc, panel, before);
                            }
                        }
                    }
                    await this.postState(doc, panel);
                    return;
                }

                case 'addTable': {
                    const t = newTableSpec(doc.spec);
                    t.x = typeof msg.x === 'number' ? Math.max(0, Math.round(msg.x)) : 40;
                    t.y = typeof msg.y === 'number' ? Math.max(0, Math.round(msg.y)) : 40;
                    doc.spec.tables.push(t);
                    this.notifyEdit(doc, panel, before);
                    await this.postState(doc, panel);
                    return;
                }

                case 'addColumn': {
                    const t = findTable(doc.spec, String(msg.table ?? ''));
                    if (t) {
                        t.columns.push(newColumnSpec(t));
                        this.notifyEdit(doc, panel, before);
                    }
                    await this.postState(doc, panel);
                    return;
                }

                case 'removeTable': {
                    const idx = doc.spec.tables.findIndex((x) => x.name === String(msg.name ?? ''));
                    if (idx >= 0) {
                        doc.spec.tables.splice(idx, 1);
                        this.notifyEdit(doc, panel, before);
                    }
                    await this.postState(doc, panel);
                    return;
                }

                case 'removeColumn': {
                    const t = findTable(doc.spec, String(msg.table ?? ''));
                    if (t) {
                        if (t.columns.length <= 1) {
                            await this.postStatus(panel, 'A table needs at least one column.');
                        } else {
                            const idx = t.columns.findIndex((x) => x.name === String(msg.column ?? ''));
                            if (idx >= 0) { t.columns.splice(idx, 1); this.notifyEdit(doc, panel, before); }
                        }
                    }
                    await this.postState(doc, panel);
                    return;
                }

                case 'moveTable': {
                    const t = findTable(doc.spec, String(msg.name ?? ''));
                    if (t) {
                        t.x = typeof msg.x === 'number' ? Math.max(0, Math.round(msg.x)) : t.x;
                        t.y = typeof msg.y === 'number' ? Math.max(0, Math.round(msg.y)) : t.y;
                        this.notifyEdit(doc, panel, before);
                    }
                    await this.postState(doc, panel);
                    return;
                }

                case 'bind': {
                    const t = findTable(doc.spec, String(msg.table ?? ''));
                    const control = String(msg.control ?? '');
                    if (t && control) {
                        const proj = findProject(doc.uri);
                        const scanned = proj ? scanBindableControls(path.dirname(proj.projectUri.fsPath)) : [];
                        const ctrl = scanned.find((c) => c.name === control);
                        const axaml = ctrl?.axamlPath;
                        if (!axaml) {
                            await this.postStatus(panel, `Couldn't find control "${control}" in the project.`);
                        } else if (t.boundTo === control) {
                            // The .adset marker is set, but the code-behind binding line may be
                            // missing (e.g. the project was recreated after binding). Re-write it
                            // so the binding actually takes effect instead of just saying "already bound".
                            const b = { datasetName: doc.spec.name, tableName: t.name, controlName: control, controlType: ctrl.type as DataSetBindingRef['controlType'] };
                            if (!hasDataSetBinding(vscode.Uri.file(axaml), b)) {
                                await bindControlToDataSet(vscode.Uri.file(axaml), b);
                                if (ctrl.type === 'DataGrid') ensureDataGridAutoGenerateColumns(axaml, control);
                                const treeNote = ctrl.type === 'TreeView' ? this.prepareTree(axaml, control) : '';
                                await this.postStatus(panel, `Re-wrote the binding to ${control} (the code-behind line was missing).${treeNote}`);
                            } else {
                                await this.postStatus(panel, `Already bound to ${control}.`);
                            }
                        } else {
                            // A control already claimed by another table/dataset can't be re-bound.
                            const claimedElsewhere = proj
                                ? scanBoundMarkers(path.dirname(proj.projectUri.fsPath), doc.spec).has(control)
                                : false;
                            if (claimedElsewhere) {
                                await this.postStatus(panel, `"${control}" is already bound to another table — un-bind it there first.`);
                            } else {
                                // A TreeView needs a shape before it can be bound: node text plus either an
                                // Id + Parent pair or a Level/Path column. Said here, at the moment of binding,
                                // because it is the only place a novice will look for it.
                                if (ctrl.type === 'TreeView' && !canBindToTree(t)) {
                                    await this.postStatus(panel,
                                        `"${control}" is a TreeView: give the table a shape first — set a column's `
                                        + 'Tree role to "Node text (Name)". Add "Id" and "Parent" (or a "Level or '
                                        + 'path" column) only if the rows nest.');
                                    return;
                                }
                                const filePath = await bindControlToDataSet(vscode.Uri.file(axaml), {
                                    datasetName: doc.spec.name, tableName: t.name, controlName: control, controlType: ctrl.type as DataSetBindingRef['controlType']
                                });
                                if (filePath) {
                                    t.boundTo = control;
                                    t.boundToType = ctrl.type as DataTableSpec['boundToType'];
                                    // Every bound table is SQLite-backed: a table with no storage of its
                                    // own defaults to the shared per-DataSet database file (created on the
                                    // app's first run, named after the DataSet).
                                    if (!t.sqlite) t.sqlite = { file: defaultDbFile(doc.spec) };
                                    // DataGrid: AutoGenerateColumns defaults to False in Avalonia, so make
                                    // sure the XAML carries it, or the bound grid shows no columns/rows.
                                    if (ctrl.type === 'DataGrid') ensureDataGridAutoGenerateColumns(axaml, control);
                                    // A TreeView also needs a template and no inline nodes; the note rides the
                                    // status line below rather than being posted here (see prepareTree).
                                    const treeNote = ctrl.type === 'TreeView' ? this.prepareTree(axaml, control) : '';
                                    // Regenerate the DataSet class so the newly bound table gets its sample row.
                                    const gen = await this.writeGeneratedFiles(doc);
                                    this.notifyEdit(doc, panel, before);
                                    await this.postStatus(panel, `Bound ${t.name} to ${control} (${path.basename(filePath)})${gen ? `; regenerated ${gen}.` : ''}${treeNote}`);
                                } else {
                                    await this.postStatus(panel, `Couldn't write the code-behind for ${control}.`);
                                }
                            }
                        }
                    }
                    await this.postState(doc, panel);
                    return;
                }

                case 'unbind': {
                    const t = findTable(doc.spec, String(msg.table ?? ''));
                    if (t && t.boundTo) {
                        const control = t.boundTo;
                        const proj = findProject(doc.uri);
                        const scanned = proj ? scanBindableControls(path.dirname(proj.projectUri.fsPath)) : [];
                        const ctrl = scanned.find((c) => c.name === control);
                        const axaml = ctrl?.axamlPath;
                        if (axaml) {
                            await unbindControlFromDataSet(vscode.Uri.file(axaml), {
                                datasetName: doc.spec.name, tableName: t.name, controlName: control, controlType: ctrl.type as DataSetBindingRef['controlType']
                            });
                        }
                        t.boundTo = null;
                        t.boundToType = null;
                        // Regenerate the DataSet class so the un-bound table loses its sample row.
                        const gen = await this.writeGeneratedFiles(doc);
                        this.notifyEdit(doc, panel, before);
                        await this.postStatus(panel, `Un-bound ${t.name}.${gen ? ` Regenerated ${gen}.` : ''}`);
                    }
                    await this.postState(doc, panel);
                    return;
                }

                case 'setTableProp': {
                    const t = findTable(doc.spec, String(msg.table ?? ''));
                    const prop = String(msg.prop ?? '');
                    if (t && prop === 'storage') {
                        const v = String(msg.value ?? '');
                        if (v === 'sqlite') {
                            if (!isSqliteTable(t)) {
                                t.sqlite = { file: (t.sqlite && t.sqlite.file) || defaultDbFile(doc.spec) };
                                this.notifyEdit(doc, panel, before);
                            }
                        } else if (t.sqlite) {
                            t.sqlite = null;
                            this.notifyEdit(doc, panel, before);
                        }
                    } else if (t && prop === 'dbFile') {
                        const v = String(msg.value ?? '').trim();
                        if (v) {
                            t.sqlite = { ...((t.sqlite && { file: t.sqlite.file }) || { file: '' }), file: v };
                            this.notifyEdit(doc, panel, before);
                        }
                    } else if (t && prop === 'connectionString') {
                        const v = String(msg.value ?? '').trim();
                        t.sqlite = { file: (t.sqlite && t.sqlite.file) || defaultDbFile(doc.spec), connectionString: v || undefined };
                        this.notifyEdit(doc, panel, before);
                    }
                    await this.postState(doc, panel);
                    return;
                }

                case 'sqliteBrowse': {
                    const t = findTable(doc.spec, String(msg.table ?? ''));
                    const proj = findProject(doc.uri);
                    const projectDir = proj ? path.dirname(proj.projectUri.fsPath) : undefined;
                    const picked = await vscode.window.showOpenDialog({
                        canSelectMany: false, canSelectFolders: false, openLabel: 'Use this SQLite file',
                        filters: { 'SQLite database': ['db', 'sqlite', 'sqlite3'] },
                        defaultUri: projectDir ? vscode.Uri.file(projectDir) : undefined,
                        title: t ? `SQLite file for ${t.name}` : 'SQLite database file'
                    });
                    if (t && picked && picked[0]) {
                        // Rule: an existing .db is used IN PLACE — store the full absolute path so the
                        // app opens/edits exactly that file (never a copy next to the exe).
                        const p = picked[0].fsPath;
                        let tableName: string | undefined;
                        try {
                            const client = await this.host.getClient();
                            const tabs = await client.sqliteTables(p);
                            const nameLower = t.name.toLowerCase();
                            if (!tabs.some((x) => x.name.toLowerCase() === nameLower) && tabs.length === 1) {
                                tableName = tabs[0].name; // single-table file: map to that real table
                            }
                        } catch { /* the file is stored regardless */ }
                        t.sqlite = tableName ? { file: p, tableName } : { file: p };
                        this.notifyEdit(doc, panel, before);
                        await this.postState(doc, panel);
                        await this.postStatus(panel, `Using SQLite file for ${t.name}: ${p}`);
                    }
                    return;
                }

                case 'sqliteQuery': {
                    // Design-time preview: run a read-only SELECT against the table's .db via the host.
                    const t = findTable(doc.spec, String(msg.table ?? ''));
                    if (t && isSqliteTable(t)) {
                        const proj = findProject(doc.uri);
                        const projectDir = proj ? path.dirname(proj.projectUri.fsPath) : undefined;
                        const dbPath = resolveDbPath(projectDir, t.sqlite!.file);
                        if (!fs.existsSync(dbPath)) {
                            await panel.webview.postMessage({ type: 'sqliteResult', table: t.name, ok: false, error: `Database file not found: ${dbPath}` });
                            return;
                        }
                        try {
                            const client = await this.host.getClient();
                            const sql = (typeof msg.sql === 'string' && msg.sql.trim()) ? msg.sql : `SELECT * FROM "${sqliteTableName(t)}" ORDER BY rowid`;
                            const res = await client.sqliteQuery(dbPath, sql, 500);
                            await panel.webview.postMessage({ type: 'sqliteResult', table: t.name, ok: true, columns: res.columns, rows: res.rows, sql, dbFile: path.basename(dbPath) });
                        } catch (e) {
                            await panel.webview.postMessage({ type: 'sqliteResult', table: t.name, ok: false, error: e instanceof Error ? e.message : String(e) });
                        }
                    }
                    return;
                }

                case 'sqliteImport': {
                    // Reverse path: create .adset tables from an existing .db.
                    const proj = findProject(doc.uri);
                    const projectDir = proj ? path.dirname(proj.projectUri.fsPath) : undefined;
                    const picked = await vscode.window.showOpenDialog({
                        canSelectMany: false, canSelectFolders: false, openLabel: 'Import tables',
                        filters: { 'SQLite database': ['db', 'sqlite', 'sqlite3'] },
                        defaultUri: projectDir ? vscode.Uri.file(projectDir) : undefined,
                        title: 'Import tables from a SQLite database'
                    });
                    if (!picked || !picked[0]) return;
                    try {
                        const client = await this.host.getClient();
                        const tables = await client.sqliteTables(picked[0].fsPath);
                        if (!tables.length) { await this.postStatus(panel, 'No tables found in that database.'); return; }
                        // Imported tables stay connected to the source .db: store the file (project-
                        // relative when possible) so binding one reads/writes the REAL rows, not the
                        // sample/XML demo store.
                        let srcFile = picked[0].fsPath;
                        if (projectDir) {
                            const rootPrefix = projectDir + path.sep;
                            if (srcFile.startsWith(rootPrefix)) srcFile = path.relative(projectDir, srcFile);
                        }
                        let added = 0;
                        for (const st of tables) {
                            const cols: DataColumnSpec[] = st.columns.map((cc) => ({
                                name: sanitizeName(cc.name || 'Column'),
                                type: sqliteAffinityToType(cc.type),
                                caption: cc.name || '',
                                allowNull: !cc.notNull,
                                sampleValue: null
                            }));
                            // De-duplicate column names inside the imported table.
                            const used = new Set<string>();
                            for (const col of cols) {
                                let n = col.name;
                                let i = 1;
                                while (used.has(n.toLowerCase())) { i += 1; n = `${col.name}${i}`; }
                                used.add(n.toLowerCase());
                                col.name = n;
                            }
                            const pks = st.columns.filter((cc) => cc.isPk).map((cc) => sanitizeName(cc.name || ''));
                            const keyColumn = (pks.length === 1 && cols.some((c) => c.name === pks[0])) ? pks[0] : null;
                            doc.spec.tables.push({
                                name: uniqueTableName(doc.spec, st.name),
                                x: 60 + added * 26, y: 60 + added * 26,
                                columns: cols, keyColumn, boundTo: null, boundToType: null, undoRedoDepth: 5,
                                sqlite: { file: srcFile, tableName: st.name }
                            });
                            added += 1;
                        }
                        this.notifyEdit(doc, panel, before);
                        await this.postState(doc, panel);
                        await this.postStatus(panel, `Imported ${added} table${added === 1 ? '' : 's'} from ${path.basename(picked[0].fsPath)} (SQLite-backed).`);
                    } catch (e) {
                        await this.postStatus(panel, 'SQLite import failed: ' + (e instanceof Error ? e.message : String(e)));
                    }
                    return;
                }

                case 'getControls': {
                    // Refresh the bindable-controls list (e.g. a control was placed/saved since
                    // the designer last pushed state) without changing the schema.
                    await panel.webview.postMessage({ type: 'controls', controls: this.controlsList(doc) });
                    return;
                }

                case 'generate': {
                    await this.generateCode(doc, panel);
                    return;
                }

                case 'removeDataSet': {
                    await this.removeDataSet(doc, panel);
                    return;
                }
            }
        } catch (err) {
            void vscode.window.showErrorMessage('DataSet designer error: ' + (err instanceof Error ? err.message : String(err)));
        }
    }

    private notifyEdit(doc: DataSetDocument, panel: vscode.WebviewPanel, before: string): void {
        const after = serializeDataSet(doc.spec);
        if (before === after) return;
        this.pushHistory(doc, after);
        this._onDidChangeCustomDocument.fire({
            document: doc,
            label: 'DataSet designer edit',
            undo: () => { doc.spec = parseDataSet(before); void this.postState(doc, panel); },
            redo: () => { doc.spec = parseDataSet(after); void this.postState(doc, panel); }
        });
    }

    /** Records a new post-edit spec state (drops the redo branch, caps at 6 states = 5 undos). */
    private pushHistory(doc: DataSetDocument, specText: string): void {
        const key = doc.uri.toString();
        const h = this.history.get(key) ?? { states: [], index: -1 };
        h.states.length = h.index + 1; // drop redo branch
        h.states.push(specText);
        if (h.states.length > 6) h.states.shift();
        h.index = h.states.length - 1;
        this.history.set(key, h);
    }

    /** Undo / redo: restore a serialized-spec snapshot and repaint the designer. */
    private async undoRedo(doc: DataSetDocument, panel: vscode.WebviewPanel, isRedo: boolean): Promise<void> {
        const h = this.history.get(doc.uri.toString());
        if (!h || h.states.length === 0) return;
        const target = isRedo ? h.index + 1 : h.index - 1;
        if (target < 0 || target >= h.states.length) return;
        h.index = target;
        doc.spec = parseDataSet(h.states[target]);
        await this.postState(doc, panel);
    }

    /** The project's bindable controls, each flagged `bound` if any dataset claims it. */
    private controlsList(doc: DataSetDocument): { name: string; type: string; bound: boolean }[] {
        const proj = findProject(doc.uri);
        if (!proj) return [];
        const folder = path.dirname(proj.projectUri.fsPath);
        const controls = scanBindableControls(folder);
        const markers = scanBoundMarkers(folder, doc.spec);
        return controls.map((c) => ({ name: c.name, type: c.type, bound: markers.has(c.name) }));
    }

    private async postState(doc: DataSetDocument, panel: vscode.WebviewPanel): Promise<void> {
        await panel.webview.postMessage({ type: 'state', spec: doc.spec, controls: this.controlsList(doc) });
    }

    /**
     * After binding a table to a TreeView (2026-09-18): make sure the form can show a tree at all — see
     * `ensureTreeItemTemplate`. Returns a fragment for the caller's status line, or '' when nothing had to
     * change: this must NOT post a status of its own, because the caller's "Bound …" line is posted right
     * after and would replace it (the inline-node removal is exactly the note the user has to see).
     */
    private prepareTree(axaml: string, control: string): string {
        const what = ensureTreeItemTemplate(axaml, control);
        if (what === 'template') return ' Added the tree template.';
        if (what === 'both') return ' Added the tree template and removed the inline nodes (a bound TreeView can\'t hold both).';
        if (what === 'cleared') return ' Removed the inline nodes (a bound TreeView can\'t hold both).';
        return '';
    }

    private async postStatus(panel: vscode.WebviewPanel, message: string): Promise<void> {
        await panel.webview.postMessage({ type: 'status', message });
    }

    // ---------------------------------------------------------------- generate
    /** Writes the runtime-construction class (C#/VB, auto-detected) + .xsd next to the .adset. */
    /** Writes the generated DataSet class (.cs/.vb) + .xsd next to the .adset. Returns the file names, or null on failure. */
    private async writeGeneratedFiles(doc: DataSetDocument): Promise<string | null> {
        const proj = findProject(doc.uri);
        const language = proj?.language ?? 'cs';
        const rootNamespace = proj?.rootNamespace || doc.spec.name;
        const folder = path.dirname(doc.uri.fsPath);
        const base = doc.spec.name;
        const codeUri = vscode.Uri.file(path.join(folder, language === 'vb' ? `${base}.vb` : `${base}.cs`));
        const xsdUri = vscode.Uri.file(path.join(folder, `${base}.xsd`));
        const code = language === 'vb' ? generateVb(doc.spec, rootNamespace) : generateCs(doc.spec, rootNamespace);
        const xsd = generateXsd(doc.spec);
        // One copy of the shared runtime helpers per folder (see consolidateRuntimeHelpers): a second
        // DataSet in the same project otherwise declares RuntimeStorage/DatabaseAdapter again and the build
        // fails with CS0101 (BC30179 in VB). A duplicate that already exists is repaired here, so one
        // 'Generate Code' is enough to fix such a project.
        const siblings: string[] = [];
        try {
            for (const e of fs.readdirSync(folder)) {
                if (!new RegExp(`\\.${language}$`, 'i').test(e)) continue;
                const p = path.join(folder, e);
                if (p !== codeUri.fsPath && isGeneratedDataSetFile(p)) siblings.push(p);
            }
        } catch { /* unreadable folder: leave the other files alone */ }
        const settled = consolidateRuntimeHelpers(
            [{ file: codeUri.fsPath, text: code }, ...siblings.map((p) => ({ file: p, text: readText(p) }))],
            language
        );
        const codeOut = settled[0].text;
        try {
            await vscode.workspace.fs.writeFile(codeUri, Buffer.from(codeOut, 'utf8'));
            await vscode.workspace.fs.writeFile(xsdUri, Buffer.from(xsd, 'utf8'));
            // A sibling is written back only when it really lost a duplicate copy of the helpers.
            for (let i = 1; i < settled.length; i++) {
                if (settled[i].text === readText(settled[i].file)) continue;
                await vscode.workspace.fs.writeFile(
                    vscode.Uri.file(settled[i].file), Buffer.from(settled[i].text, 'utf8'));
            }
            // A SQLite-bound table needs the SQLite packages in the project to build/run.
            ensureSqlitePackages(proj ?? undefined, doc.spec);
            return [path.basename(codeUri.fsPath), path.basename(xsdUri.fsPath)].join(' + ');
        } catch {
            return null;
        }
    }

    private async generateCode(doc: DataSetDocument, panel: vscode.WebviewPanel): Promise<void> {
        const proj = findProject(doc.uri);
        const language = proj?.language ?? 'cs';
        const names = await this.writeGeneratedFiles(doc);
        if (!names) {
            void vscode.window.showErrorMessage('Could not write the generated files.');
            return;
        }
        // Persist the schema too — the generated class is derived from it, so the .adset on disk
        // must match (otherwise the regenerated code can reference columns the saved schema lacks
        // and, worse, an existing .db is left out of step with the code until the next save).
        try {
            if (doc.parseError) {
                void vscode.window.showErrorMessage(
                    `Not saving ${path.basename(doc.uri.fsPath)}: it could not be read as a DataSet ` +
                    `(${doc.parseError}), so writing the schema now would replace the file with an ` +
                    'empty one. The generated files were written — fix or delete the .adset, then retry.');
            } else {
                await vscode.workspace.fs.writeFile(doc.uri, Buffer.from(serializeDataSet(doc.spec), 'utf8'));
                doc.markSaved();
            }
        } catch { /* the generated files still exist */ }
        await this.postStatus(panel, `Generated ${names}.`);
        const lang = language === 'vb' ? 'VB.NET' : 'C#';
        void vscode.window.showInformationMessage(
            proj
                ? `Generated ${names} (${lang}) and saved ${path.basename(doc.uri.fsPath)}.`
                : `Generated ${names} as ${lang} — no .csproj/.vbproj found nearby, so it isn't part of a build yet.`
        );
    }

    /** 'Remove DataSet': after a modal warning, strips every code-behind binding this DataSet's
     *  tables created, deletes the .adset + generated class/.xsd, deletes the DataSet's OWN
     *  auto-created default .db (project + bin/Debug + bin/Release copies — never a user-browsed /
     *  per-table / external .db, those are only listed for the user to delete by hand), then closes
     *  the designer panel. */
    private async removeDataSet(doc: DataSetDocument, panel: vscode.WebviewPanel): Promise<void> {
        try {
            const folder = path.dirname(doc.uri.fsPath);
            const base = doc.spec.name;
            const proj = findProject(doc.uri);
            const projectFolder = proj ? path.dirname(proj.projectUri.fsPath) : folder;

            // --- what the removal will delete ---
            const filesToDelete: string[] = [doc.uri.fsPath]; // the .adset itself
            const generated: string[] = [];
            for (const ext of ['cs', 'vb']) {
                const p = path.join(folder, `${base}.${ext}`);
                if (fs.existsSync(p)) { generated.push(p); filesToDelete.push(p); }
            }
            const xsd = path.join(folder, `${base}.xsd`);
            if (fs.existsSync(xsd)) filesToDelete.push(xsd);

            // The DataSet's OWN auto-created default db (<DataSet>.db): delete existing copies in the
            // project folder and under bin/... (the app creates the file next to the exe on first run).
            const defaultDb = `${base}.db`;
            const defaultDbCopies: string[] = [];
            const addIfExists = (dir: string): void => {
                if (!dir) return;
                const p = path.join(dir, defaultDb);
                if (fs.existsSync(p)) { defaultDbCopies.push(p); filesToDelete.push(p); }
            };
            addIfExists(projectFolder);
            for (const cfg of ['Debug', 'Release']) {
                for (const tfm of ['net8.0', 'net9.0', 'net10.0']) addIfExists(path.join(projectFolder, 'bin', cfg, tfm));
            }

            // User-browsed / per-table .db files are NEVER auto-deleted (they may be shared with
            // other apps or datasets) — list them so the user can delete them manually if they want.
            const keptDbs = new Set<string>();
            for (const t of doc.spec.tables) {
                const f = t.sqlite && t.sqlite.file;
                if (f && path.basename(f) !== defaultDb) keptDbs.add(f);
            }

            // --- bindings this DataSet's tables created in form code-behind ---
            const scanned = scanBindableControls(projectFolder);
            const bindings: { table: string; control: string; type: string; axamlPath: string }[] = [];
            for (const t of doc.spec.tables) {
                if (!t.boundTo) continue;
                const c = scanned.find((x) => x.name === t.boundTo);
                if (c) bindings.push({ table: t.name, control: c.name, type: c.type, axamlPath: c.axamlPath });
            }

            // --- modal warning listing exactly what will happen ---
            const lines: string[] = [];
            lines.push(`**Remove DataSet "${doc.spec.name}"?**`);
            lines.push('');
            lines.push(`This deletes:`);
            lines.push(`  • schema  ${path.basename(doc.uri.fsPath)}`);
            if (generated.length) lines.push(`  • code    ${generated.map((p) => path.basename(p)).join(', ')}`);
            if (defaultDbCopies.length) {
                const rel = defaultDbCopies.map((p) => path.relative(projectFolder, p) || p).join(', ');
                lines.push(`  • database ${defaultDb}  (${rel})`);
            } else {
                lines.push(`  • database ${defaultDb}  (none found on disk)`);
            }
            if (bindings.length) lines.push(`  • un-binds ${bindings.length} control${bindings.length === 1 ? '' : 's'}: ${bindings.map((b) => `${b.control} (${b.table})`).join(', ')}`);
            if (keptDbs.size) {
                lines.push('');
                lines.push(`Database files NOT deleted (delete them yourself if no longer used):`);
                for (const f of keptDbs) lines.push(`  • ${f}`);
            }
            lines.push('');
            lines.push('This cannot be undone.');
            const answer = await vscode.window.showWarningMessage(lines.join('\n'), { modal: true }, 'Remove DataSet', 'Cancel');
            if (answer !== 'Remove DataSet') return;

            // --- strip code-behind bindings first, so the project still compiles once the class is gone ---
            for (const b of bindings) {
                try {
                    await unbindControlFromDataSet(vscode.Uri.file(b.axamlPath), {
                        datasetName: doc.spec.name, tableName: b.table, controlName: b.control,
                        controlType: b.type as DataSetBindingRef['controlType']
                    });
                } catch { /* best-effort — keep removing */ }
            }
            // Also strip any Data-Image bindings (Images that followed these grids' selections).
            for (const t of doc.spec.tables) {
                for (const bi of t.boundImages || []) {
                    const ax = findFormWithControl(projectFolder, bi.control);
                    if (ax) {
                        try { await unbindImageFromGrid(vscode.Uri.file(ax), bi.control); }
                        catch { /* best-effort */ }
                    }
                }
            }

            // --- delete the files ---
            let deleted = 0;
            const failed: string[] = [];
            for (const p of filesToDelete) {
                try { await vscode.workspace.fs.delete(vscode.Uri.file(p)); deleted += 1; }
                catch { failed.push(path.basename(p)); }
            }

            // --- close the DataSet designer ---
            panel.dispose();

            void vscode.window.showInformationMessage(
                `Removed DataSet "${doc.spec.name}" — deleted ${deleted} file${deleted === 1 ? '' : 's'}`
                + (bindings.length ? ` and un-bound ${bindings.length} control${bindings.length === 1 ? '' : 's'}` : '')
                + (failed.length ? `. Could not delete: ${failed.join(', ')}` : '') + '.'
            );
        } catch (e) {
            void vscode.window.showErrorMessage('Remove DataSet failed: ' + (e instanceof Error ? e.message : String(e)));
        }
    }

    // ---------------------------------------------------------------- save etc.
    async saveCustomDocument(document: DataSetDocument): Promise<void> {
        await vscode.workspace.fs.writeFile(document.uri, Buffer.from(serializeDataSet(document.spec), 'utf8'));
        document.markSaved();
    }

    async saveCustomDocumentAs(document: DataSetDocument, destination: vscode.Uri): Promise<void> {
        await vscode.workspace.fs.writeFile(destination, Buffer.from(serializeDataSet(document.spec), 'utf8'));
        document.markSaved();
    }

    async revertCustomDocument(document: DataSetDocument): Promise<void> {
        const data = await vscode.workspace.fs.readFile(document.uri);
        document.spec = parseDataSet(Buffer.from(data).toString('utf8'));
        const panel = this.panels.get(document.uri.toString());
        if (panel) await this.postState(document, panel);
    }

    async backupCustomDocument(document: DataSetDocument, context: vscode.CustomDocumentBackupContext): Promise<vscode.CustomDocumentBackup> {
        const data = Buffer.from(serializeDataSet(document.spec), 'utf8');
        await vscode.workspace.fs.writeFile(context.destination, data);
        return {
            id: context.destination.toString(),
            delete: () => vscode.workspace.fs.delete(context.destination)
        };
    }

    // ---------------------------------------------------------------- webview
    private webviewHtml(wv: vscode.Webview): string {
        const cssUri = wv.asWebviewUri(vscode.Uri.joinPath(this.context.extensionUri, 'media', 'dataSet.css'));
        const jsUri = wv.asWebviewUri(vscode.Uri.joinPath(this.context.extensionUri, 'media', 'dataSet.js'));
        const csp = [
            "default-src 'none'",
            `img-src ${wv.cspSource} data:`,
            `style-src ${wv.cspSource} 'unsafe-inline'`,
            `script-src ${wv.cspSource}`,
            `font-src ${wv.cspSource}`
        ].join('; ');
        return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta http-equiv="Content-Security-Policy" content="${csp}"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<link rel="stylesheet" href="${cssUri}"/>
<title>DataSet Designer</title>
</head>
<body>
  <div class="toolbar">
    <span class="brand">DataSet</span>
    <label for="ds-name-input">Name</label>
    <input id="ds-name-input" type="text" spellcheck="false" readonly title="The DataSet name is fixed when the .adset is created. To rename: Remove DataSet… then create a new one."/>
    <button id="btnAddTable" title="Add a table">+ Table</button>
    <button id="btnGenerate" title="Generate the runtime DataSet class (.cs/.vb) + .xsd">Generate Code</button>
    <button id="btnImportSqlite" title="Create tables from an existing SQLite database file (.db)">Import SQLite…</button>
    <button id="btnRemoveDataSet" class="remove" title="Remove this DataSet entirely: deletes the .adset + generated class/.xsd, un-binds its controls, and deletes its auto-created .db (project + bin copies).">Remove DataSet…</button>
    <span id="status" class="status"></span>
  </div>
  <div class="main">
    <div id="canvas">
      <div class="empty-hint">Right-click the canvas to add a table.</div>
    </div>
    <div id="props"></div>
  </div>
  <div id="dsSqliteModal" class="modal" hidden>
    <div class="modal-box">
      <h3 id="dsSqliteTitle">SQLite data</h3>
      <div id="dsSqliteFile" class="sqlite-file-label"></div>
      <div id="dsSqliteStatus" class="sqlite-status"></div>
      <textarea id="dsSqliteSql" rows="2" spellcheck="false" title="Read-only SELECT to preview (max 500 rows)"></textarea>
      <div class="modal-buttons">
        <button id="dsSqliteRun">Run</button>
        <button id="dsSqliteClose">Close</button>
      </div>
      <div id="dsSqliteBody"></div>
    </div>
  </div>
  <div id="ctxmenu"></div>
  <script src="${jsUri}"></script>
</body>
</html>`;
    }
}

/** "Avalonia: New DataSet…" — creates a .adset (with a starter table) and opens it in the designer. */
export async function newDataSet(context: vscode.ExtensionContext): Promise<void> {
    const name = await vscode.window.showInputBox({
        prompt: 'Name of the new DataSet (e.g. MyData) — also the generated class name.',
        value: 'MyData',
        validateInput: (s) => (isValidIdentifier(s.trim()) ? undefined : 'Use letters, numbers and underscore only (no spaces).')
    });
    if (!name) return;
    const clean = name.trim();

    let folder: vscode.Uri | undefined;
    if (vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length > 0) {
        folder = vscode.workspace.workspaceFolders[0].uri;
    } else {
        const picked = await vscode.window.showOpenDialog({ canSelectFolders: true, openLabel: 'Create DataSet here' });
        folder = picked && picked[0];
    }
    if (!folder) return;

    // If a database file with this name already exists, warn that bound tables will write to it.
    if (defaultDbExists(folder.fsPath, clean)) {
        const go = await vscode.window.showWarningMessage(
            `A database file "${clean}.db" already exists in this folder. Tables you bind to this DataSet will read/write that EXISTING file. Continue?`,
            { modal: true }, 'Continue', 'Cancel');
        if (go !== 'Continue') return;
    }

    const uri = vscode.Uri.joinPath(folder, `${clean}.adset`);
    let exists = false;
    try { await vscode.workspace.fs.stat(uri); exists = true; } catch { /* not found */ }

    if (!exists) {
        const spec = defaultDataSetSpec(clean);
        await vscode.workspace.fs.writeFile(uri, Buffer.from(serializeDataSet(spec), 'utf8'));
    }
    void vscode.commands.executeCommand('vscode.openWith', uri, DataSetEditorProvider.viewType, { preview: false });
}

/** Opens an existing .adset in the DataSet designer. */
export async function openDataSet(uri?: vscode.Uri): Promise<void> {
    const target = uri ?? vscode.window.activeTextEditor?.document.uri;
    if (!target) return;
    void vscode.commands.executeCommand('vscode.openWith', target, DataSetEditorProvider.viewType);
}
