/**
 * xamlHeader.ts — the notice every generated `.axaml` carries.
 *
 * A designer form is a two-way file: the designer reads it, edits it through its model and writes
 * it back **re-formatted** (Attribute order, indentation, in-memory names stripped, the DataGrid's
 * `AutoGenerateColumns` marker, …). Hand-edits are therefore fragile: they can be re-formatted away,
 * and structural edits (renaming a control, adding a row by hand) are exactly what leaves the
 * code-behind out of step — the failures the "🩺 Code Fix…" checker exists for. So every file the
 * extension creates starts with this comment, telling the user where to make the change.
 *
 * `withDesignerHeader` is idempotent and applied at BOTH ends:
 *   - every generated file (new project, new form, App.axaml), and
 *   - every save from the designer (so a file that was created elsewhere — or whose header was
 *     removed by hand — gains it too, and re-saving never duplicates it).
 */
const HEADER = '<!-- Do NOT edit this file manually - Use the Designer to make changes -->';

/** The header line as written (exported for tests and for the doc/README wording). */
export const XAML_DESIGNER_HEADER = HEADER;

/**
 * Returns `text` with exactly one designer header at the top: removes every existing copy first
 * (these can end up anywhere once the designer's model has been round-tripped), keeps a leading
 * `<?xml …?>` declaration as the very first line, and preserves a byte-order mark if there was one.
 */
export function withDesignerHeader(text: string): string {
    const hadBom = text.charCodeAt(0) === 0xFEFF;
    let body = text.replace(/\uFEFF/g, '');
    if (body.includes(HEADER)) {
        body = body.split('\n').filter((line) => line.trim() !== HEADER).join('\n');
        body = body.replace(/^[ \t]*\r?\n/, ''); // drop the blank line the removal can leave at the top
    }
    const decl = /^\s*<\?xml[^>]*\?>\s*\r?\n/.exec(body);
    const head = hadBom ? '\uFEFF' : '';
    if (decl) return `${head}${decl[0].trimEnd()}\n${HEADER}\n${body.slice(decl[0].length)}`;
    return `${head}${HEADER}\n${body}`;
}
